packages/neo-one-server-plugin-network/src/node/NEOBlockchainNodeAdapter.js

Changed fix from detached: true to windowsHide: true

Nodes no longer create pop up windows on Windows OS -windowsHide: true

---

packages/neo-one-cli/src/interactive/createCRUD.js

Added functionality which asks the user to confirm a delete command in the interactive CLI
The user will now have some barrier to accidentally deleting things they do not wish to delete.  
#20

Added basic delete prompt functionality

---

packages/neo-one-client/src/__tests__/user/converters/attribute.test.js
packages/neo-one-client/src/__tests__/user/converters/input.test.js
packages/neo-one-client/src/__tests__/user/converters/output.test.js
packages/neo-one-client/src/__tests__/user/converters/witness.test.js

Added tests for converters in client

---

packages/neo-one-client/src/__tests__/Client.test.js
packages/neo-one-client/src/__tests__/ReadClient.test.js
packages/neo-one-client/src/__tests__/__snapshots__/utils.test.js.snap
packages/neo-one-client/src/__tests__/abi.test.js
packages/neo-one-client/src/__tests__/args.test.js
packages/neo-one-client/src/__tests__/helpers.test.js
packages/neo-one-client/src/__tests__/preconfigured.test.js
packages/neo-one-client/src/__tests__/utils.test.js
packages/neo-one-client/src/args.js

Added client testing

---

packages/neo-one-client/src/__tests__/user/LocalUserAccountProvider.test.js
packages/neo-one-client/src/__tests__/user/__snapshots__/LocalUserAccountProvider.test.js.snap
packages/neo-one-client/src/user/LocalUserAccountProvider.js

Add LocalUserAccountProvider testing

---

packages/neo-one-client/src/__tests__/Client.test.js
packages/neo-one-client/src/__tests__/__snapshots__/Client.test.js.snap
packages/neo-one-client/src/__tests__/provider/neoone/NEOONEDataProvider.test.js
packages/neo-one-client/src/__tests__/provider/neoone/NEOONEProvider.test.js
packages/neo-one-client/src/__tests__/provider/neoone/__snapshots__/NEOONEDataProvider.test.js.snap
packages/neo-one-client/src/__tests__/provider/neoone/__snapshots__/NEOONEProvider.test.js.snap
packages/neo-one-client/src/__tests__/sc/common.test.js
packages/neo-one-client/src/__tests__/sc/createReadSmartContract.test.js
packages/neo-one-client/src/__tests__/sc/createSmartContract.test.js
packages/neo-one-client/src/__tests__/user/keystore/LocalKeyStore.test.js
packages/neo-one-client/src/__tests__/user/keystore/LocalMemoryStore.test.js
packages/neo-one-client/src/__tests__/user/keystore/LocalStringStore.test.js
packages/neo-one-client/src/user/keystore/LocalStringStore.js

Added tests to cover holes in testing as the client was updated
#45

Client testing cleanup

---

packages/neo-one-server-plugin-wallet/package.json
packages/neo-one-server-plugin-wallet/src/bootstrap.js
yarn.lock

Used ora to create basic progress indicators for the bootstrap command.
#99

Add progress indicators to bootstrap

---

packages/neo-one-client-core/src/vm.ts
packages/neo-one-node-vm/src/__tests__/__snapshots__/syscalls.test.ts.snap
packages/neo-one-node-vm/src/__tests__/syscalls.test.ts
packages/neo-one-node-vm/src/syscalls.ts

Add 'Neo.Iterator.Create' to vm syscalls
test can be found in neo-one-node-vm/src/__tests__/syscalls.test.ts
#180

Add Neo.Iterator.Create

---

packages/neo-one-client/src/typeGuards.ts

Adds typeGuards.ts to neo-one-client.

Add type guards for client types

---

packages/neo-one-client/src/__tests__/index.test.ts
packages/neo-one-client/src/index.ts

adds the typeguard export in neo-one-client/index.ts

adds typeguards as an export so we can use them in neotracker

---

packages/neo-one-node-protocol/src/Node.ts

We change a sorting pattern in `neo-one-node-protocol/Node.ts`. Before we used:
```
_.sortBy(transactionAndFee, [
([transaction, networkFee]: [Transaction, BN]) => networkFee.divn(transaction.size).toNumber(),
([transaction]: [Transaction]) => transaction.hashHex,
]) as ReadonlyArray<[Transaction, BN]>)
```
which is pretty brutal, but if I understand correctly it just converts `networkFee`s to a number and compares them, and then breaks ties by comparing `transaction.hashHex`s.
to improve this and avoid issues with `number` size limits we want to use `BN` comparison functions instead. To simplify it all I created a classic comparison function for `TransactionAndFee = [Transaction, BN]`.
```
export interface TransactionAndFee {
readonly transaction: Transaction;
readonly networkFee: BN;
} …
```

fixes the BN comparison in trimMemBool

---

packages/neo-one-editor/src/monaco/AsyncLanguageService.ts
packages/neo-one-editor/src/monaco/features/QuickInfoAdapter.ts
packages/neo-one-editor/src/monaco/features/SignatureHelpAdapter.ts
packages/neo-one-editor/src/monaco/features/SuggestAdapter.ts
packages/neo-one-editor/src/monaco/features/utils.ts

offload ts.displayPartsToString related code to worked

---

packages/neo-one-website/src/components/content/Sidebar.tsx

Add transitions to mobile sidebar

---

packages/neo-one-editor/src/editor/toolbar/FileText.tsx
packages/neo-one-editor/src/editor/toolbar/TestSummary.tsx

Aligned text in TestDetail side of the console.  Also aligned the headers of the two sides of the console for tests.

Align text in console

---

packages/neo-one-website/src/components/tutorial/Tutorial.tsx

Fixed bug where document was accessed before a check that is is not undefined.

Fix bug where document was accessed before check

---

cypress/common/matchers.ts
cypress/integration/TokenomicsCourse.ts
packages/neo-one-editor/src/engine/test/testRunner.init.ts

check all problems in lessons 1 & 2

---

cypress/common/lessons.ts
cypress/integration/TokenomicsCourse/Lesson4/Chapter1.ts
cypress/integration/TokenomicsCourse/Lesson4/Chapter2.ts
cypress/integration/TokenomicsCourse/Lesson4/Chapter3.ts
cypress/integration/TokenomicsCourse/Lesson4/Chapter4.ts
cypress/integration/TokenomicsCourse/Lesson4/Chapter5.ts

Add tests for tokenomics lesson 4

Lesson 4 cypress tests

---

packages/neo-one-website/docs/3-api-reference/2-client.md

first section of client docs

---

packages/neo-one-website/docs/3-api-reference/2-client.md

Fills out most of the Blockchain Data section of the client api docs.

fill in more of client api docs

---

jest/base.js

suppresses getSemanticDiagnostics test on windows

---

packages/neo-one-website/docs/3-api-reference/2-client.md

update links on client.md

---

packages/neo-one-editor-server/src/__tests__/__snapshots__/resolveDependencies.test.ts.snap
packages/neo-one-editor-server/src/__tests__/resolveDependencies.test.ts

Resolve dependencies should not pass more consistently by ignoring transient dependencies.

Fixed resolveDependencies test to be more consistent

---

renovate.json

Bors handles merging only passing changes.
n/a
n/a
Automated dependency management
Might update something we don't want updated.
n/a

ci(renovate): Auto-merge dependency updates

---

packages/neo-one-website/package.json
packages/neo-one-website/src/utils/dgeniSetup.ts
packages/neo-one-website/src/utils/getReferences.ts
packages/neo-one-website/src/utils/processors/index.ts
packages/neo-one-website/src/utils/processors/textProcessor.ts
packages/neo-one-website/src/utils/templates/template.txt
packages/neo-one-website/src/utils/tokenizeDocText.ts
yarn.lock

Use dgeni to generate json files from code. Scrape these json files for ingestion into the
neo-one-website.  
Ensure json files contain expected data and that they are scraped properly. More thorough testing will be done once this is added to the front-end portion.  The website will be staged and confirm that everything looks and works as expected.
#702

docs(Reference): Use dgeni to generate docs from code

---

gulpfile.js
package.json
packages/neo-one-node-bin/package.json
scripts/DockerfileNode

connects to https://quay.io/repository/neoone/node for automated building.
#706

feat(node): add dockerfile for building node container.

---

packages/neo-one-website/package.json

Description of change
add @types/react-helmet to project in support of react-static-6.x
Issue #835
Related PR: https://github.com/neo-one-suite/neo-one/pull/831
Failing Lint report: https://circleci.com/gh/neo-one-suite/neo-one/21369?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

patch(neo-one-website) add typed react-helmet

---

tslint.json

- ban-ts-ignore
- no-default-import
Update the tslint.json to disable selected rules. 
https://github.com/neo-one-suite/neo-one/pull/852

chore(tslint): disable select tslint rules

---

jest/base.js
packages/neo-one-server-plugin-project/src/__data__/buildCommand.bootstrap.ts
packages/neo-one-server-plugin-project/src/__data__/ico/one/generated/projectID.ts
packages/neo-one-server-plugin-project/src/__data__/icojs/.onerc.json
packages/neo-one-server-plugin-project/src/__data__/icojs/one/contracts/Escrow.ts
packages/neo-one-server-plugin-project/src/__data__/icojs/one/contracts/ICO.ts
packages/neo-one-server-plugin-project/src/__data__/icojs/one/contracts/Token.ts
packages/neo-one-server-plugin-project/src/__data__/icojs/one/contracts/tsconfig.json
packages/neo-one-server-plugin-project/src/__data__/icojs/one/generated/Escrow/abi.js
packages/neo-one-server-plugin-project/src/__data__/icojs/one/generated/Escrow/contract.js
packages/neo-one-server-plugin-project/src/__data__/icojs/one/generated/ICO/abi.js
packages/neo-one-server-plugin-project/src/__data__/icojs/one/generated/ICO/contract.js
packages/neo-one-server-plugin-project/src/__data__/icojs/one/generated/Token/abi.js
packages/neo-one-server-plugin-project/src/__data__/icojs/one/generated/Token/contract.js
packages/neo-one-server-plugin-project/src/__data__/icojs/one/generated/client.js
packages/neo-one-server-plugin-project/src/__data__/icojs/one/generated/index.js
packages/neo-one-server-plugin-project/src/__data__/icojs/one/generated/projectID.js
packages/neo-one-server-plugin-project/src/__data__/icojs/one/generated/sourceMaps.js
packages/neo-one-server-plugin-project/src/__data__/icojs/one/generated/test.js
packages/neo-one-server-plugin-project/src/__e2e__/__snapshots__/buildCommandJs.test.ts.snap
packages/neo-one-server-plugin-project/src/__e2e__/buildCommandJs.test.ts
tsconfig.json

yarn jest buildCommand
yarn build
yarn neo-one reset --static-neo-one && yarn neo-one start server --static-neo-one --debug
yarn neo-one build
Support compiling to JavaScript by:
updating webpack configuration to compile to JavaScript
update buildCommand tests

feat(toolchain): e2e tests for JavaScript codegen

---

packages/neo-one-website/src/components/reference/ReferenceGrid.tsx

Update asserted code per new lint rules.
remove 'any' type casting from identified file.
Standard lint test
yarn lint
Green lint test.
https://github.com/neo-one-suite/neo-one/pull/758

chore(dep-update): Updating code style of ReferenceGrid

---

gulpfile.js
tsconfig/tsconfig.es2017.browserify.cjs.json
tsconfig/tsconfig.es2017.browserify.esm.json
tsconfig/tsconfig.esnext.browserify.esm.json

Move from gulp babel transforms to tsc custom transforms to transform rxjs imports.

build(gulpfile): Add custom transforms for rxjs imports

---

README.md

Title.
Forgot to add this when we setup the quay.io build

chore(readme): add node-image button to readme.

---

packages/neo-one-local-browser/src/utils.ts
packages/neo-one-website/courses/0-tokenomics/2-launch/0-info/package.json
packages/neo-one-website/courses/0-tokenomics/2-launch/1-balance/package.json
packages/neo-one-website/courses/0-tokenomics/2-launch/2-participate/package.json
packages/neo-one-website/courses/0-tokenomics/2-launch/3-reactive/package.json
packages/neo-one-website/courses/0-tokenomics/2-launch/4-transfer/package.json
packages/neo-one-website/courses/0-tokenomics/2-launch/5-withdraw/package.json
yarn.lock

Fixes everything
go through the courses successfully.

fix(website): fix website courses and dependencies

---

package.json
packages/neo-one-client-core/src/__tests__/AsyncBlockIterator.test.ts
packages/neo-one-client-core/src/__tests__/Client.test.ts
packages/neo-one-client-core/src/__tests__/provider/JSONRPCHTTPProvider.test.ts
packages/neo-one-client-core/src/__tests__/provider/NEOONEDataProvider.test.ts
packages/neo-one-client-core/src/__tests__/provider/NEOONEOneDataProvider.test.ts
packages/neo-one-client-core/src/__tests__/provider/NEOONEProvider.test.ts
packages/neo-one-client-core/src/__tests__/sc/createSmartContract.test.ts
packages/neo-one-client-full-core/src/__tests__/Client.test.ts
packages/neo-one-client-full-core/src/__tests__/user/LocalUserAccountProvider.test.ts
packages/neo-one-editor/src/__tests__/engine/resolve.test.ts
packages/neo-one-monitor/src/__tests__/BrowserMonitor.test.ts
yarn.lock

Upgrade to @types/jest 24.0.6.
Old tests still run.
#1035 
#1036

chore(dep): upgrade to @types/jest 24.0.6

---

package.json
packages/neo-one-developer-tools-frame/src/BlockTime.tsx
packages/neo-one-developer-tools-frame/src/ThemeProvider.tsx
packages/neo-one-editor/src/error/components/Collapsible.tsx
packages/neo-one-react-common/src/SplitPane.tsx
packages/neo-one-server-plugin-project/package.json
packages/neo-one-website/courses/0-tokenomics/2-launch/0-info/package.json
packages/neo-one-website/courses/0-tokenomics/2-launch/1-balance/package.json
packages/neo-one-website/courses/0-tokenomics/2-launch/2-participate/package.json
packages/neo-one-website/courses/0-tokenomics/2-launch/3-reactive/package.json
packages/neo-one-website/courses/0-tokenomics/2-launch/4-transfer/package.json
packages/neo-one-website/courses/0-tokenomics/2-launch/5-withdraw/package.json
yarn.lock

fix(deps): update dependency @types/react to v16.8.5

---

packages/neo-one-editor-server/package.json
packages/neo-one-editor-server/src/resolveDependencies.ts
packages/neo-one-editor-server/src/resolvePackage.ts
packages/neo-one-node-protocol/package.json
packages/neo-one-node-protocol/src/Node.ts
packages/neo-one-node-storage-cache/package.json
packages/neo-one-node-storage-cache/src/cacheStorage.ts
packages/neo-one-node-storage-cache/src/read.ts
yarn.lock

fix(deps): update dependency @types/lru-cache to v5

---

package.json
packages/neo-one-editor/src/editor/EditorHeader.tsx
packages/neo-one-editor/src/editor/toolbar/ConsoleOutput.tsx
packages/neo-one-editor/src/editor/toolbar/ProblemsView.tsx
packages/neo-one-editor/src/editor/toolbar/TestDetailError.tsx
packages/neo-one-editor/src/editor/toolbar/TestDetailList.tsx
packages/neo-one-editor/src/editor/toolbar/TestSummaryList.tsx
packages/neo-one-website/src/components/Header.tsx
packages/neo-one-website/src/components/course/chapter/Docs.tsx
packages/neo-one-website/src/components/course/chapter/DocsSolution.tsx
packages/neo-one-website/src/components/home/Home.tsx
yarn.lock

fix overflow styling in website, also update some deps in the lockfile + add a resolution for react to root package.json.

fix(website): fix overflow styling

---

gulpfile.js
tsconfig/tsconfig.es2017.browserify.cjs.json
tsconfig/tsconfig.es2017.browserify.esm.json

browserify now runs as part of the build command and will publish properly.

refactor(gulp browserify): browserify now runs as part of the build command

---

packages/neo-one-client-switch/package.json
yarn.lock

Title, want to see if doing them together has any effect. In either case, they both are having the some problem so we can consolidate.

chore(dep): update both ledger deps together

---

scripts/checkPort.js
scripts/e2e/One.js

FEW MEN DARE TACKLE THE TASK; WILL THIS FIX EVERYTHING? :thinking:
Resolves the ports to use through a more systematic approach of checking them.
What if NONE of the ports are available and rightly so? This thing will probably just OOM?

fix(CI): add port availability checks to e2e test

---

package.json
packages/neo-one-cli/package.json
packages/neo-one-client-common/src/__tests__/models/transaction/transactionModels.test.ts
packages/neo-one-client-core/package.json
packages/neo-one-client-full-core/package.json
packages/neo-one-client-switch/package.json
packages/neo-one-editor-server/package.json
packages/neo-one-http/src/createServer$.ts
packages/neo-one-monitor/src/NodeMonitor.ts
packages/neo-one-node-bin/package.json
packages/neo-one-node-consensus/package.json
packages/neo-one-node-vm/package.json
packages/neo-one-node-vm/src/__tests__/stackItem/StackItem.test.ts
packages/neo-one-server-client/package.json
yarn.lock

Renovate was deduping some stuff we weren't so it was hard to test. I pulled all the problem ones together, deduped and fixed the issues.
*UNRELATEDLY* some of my tests from the code coverage sprint were wrong so I fixed them up, heh.

chore(dep): fix a batch of dependencies

---

renovate.json

[THIS ONE SIMPLE TRICK.](https://youtu.be/9CS7j5I6aOc)
SOFTWARE DEVS HATE HIM.
THIS SHOULD DO IT
I can look at the PR page again.
none
#1352

feat(renovatebot): group renovatebot dependency updates

---

renovate.json

Add some grouping to the Renovate PRs

feat(renovate): add more renovate organization

---

renovate.json

fix(renovate): try fixing the organization again

---

renovate.json

feat(renovatebot): try organizing again

---

renovate.json

PLZZZZZ renovate do what I want. (I actually think I did it this time, saw a better example)

feat(renovate): no promises this does anything

---

renovate.json

I FIGURED OUT THE REGEX SO ORGANIZED NOW THIS IS SICK

feat(renovate): final renovate configuration

---

packages/neo-one-smart-contract-compiler/src/compile/sb/BaseScriptBuilder.ts
packages/neo-one-smart-contract-compiler/src/compile/sb/resolveJumps.ts

title, undo most recent commit

Revert "Small optimizations to bytecode size in compiler"

---

packages/neo-one-suite/package.json
packages/neo-one-website/docs/0-installation/1-environment-setup.md

title, we need to release and I'll do another pass of website docs for where we can tell people to use it.

feat(suite): add @neo-one/suite for one-line install

---

jest/base.js

chore(jest): remove deprecated config name

---

package.json
packages/neo-one-website/tutorial/tutorial.md
yarn.lock

update tutorial document with `@neo-one/suite` reference.
Add `resolve` as a resolution, see #1433
(also put our resolutions in alphabetical order)

fix(web): update website docs with @neo-one/suite

---

packages/neo-one-developer-tools-frame/package.json
packages/neo-one-smart-contract-lib/package.json
packages/neo-one-smart-contract-lib/src/__tests__/__snapshots__/RedToken.test.ts.snap
packages/neo-one-smart-contract-lib/src/__tests__/__snapshots__/TestICO.test.ts.snap
packages/neo-one-smart-contract-lib/src/__tests__/__snapshots__/TestToken.test.ts.snap

title, fix some issues from the last commit.

fix(build): fix the build

---

packages/neo-one-cli/src/InteractiveCLI.ts
packages/neo-one-server-client/src/ServerManager.ts

Fix the flashing of the CLI spinner by adding a server command to check for a newer version and using that, instead of what we did before which had the versionSpinner not being killed until *after* the server spinner had started.
```
yarn build
node ./dist/neo-one/packages/neo-one-cli/bin/neo-one version
```
or any other command and note how they don't overlap anymore.
I also moved some of the logic/text around to make it more clear when it is starting/checking for a running server.
I'm sure there are several other ways to organize this.
Less awful to look at.
#1431

fix(cli): fix cli-spinner title flashing

---

scripts/DockerfileNode

fix(node): dockerfile update

---

gulpfile.js

Chaos is a ladder. There is no organizing the gulpfile and I don't know why I ever convince myself there is.
At the very least I move some consts around for consistency and remove some unused vars. ¯\_(ツ)_/¯
Also change the `watch` command to watch both the src **AND** bin files and re-compile/re-build the bin when either changes. I notice this solved issues when rebuilding the `@neo-one/server-plugin-project` in #1481 
fix #1473

chore(gulpfile): 'tidy' the gulpfile slightly

---

.vscode/settings.json
scripts/DockerfileNode

chore(workspace): Add proper docker file setting

---

packages/neo-one-website/docs/0-installation/1-environment-setup.md
packages/neo-one-website/docs/0-installation/2-playground.md
packages/neo-one-website/tutorial/tutorial.md

The website erroneously instructs to run executables with `npm` but they need to be run with `npx` when not using `yarn`. This PR changes that instruction wherever necessary (in the Tutorial instructions and the Playground instructions). I also fixed one spot to say `npm start` instead of `npm run start`, as they are the same.
Fixes #1527 
See screenshots below or run `yarn website:start:dev-builds` then `yarn website:start:dev` to see changes.
None.
Clearer instructions.
None.
None.

Fix website instructions to use npx

---

packages/neo-one-editor/src/engine/main/initializeFileSystem.ts

fix(@neo-one/website): Fix website editor errors

---

.prettierrc
scripts/e2e/NodeEnvironment.js
scripts/e2e/One.js
scripts/test/NodeEnvironment.js

chore(ws): update .prettierrc

---

packages/neo-one-client-common/src/ScriptBuilder.ts
packages/neo-one-client-common/src/common.ts
packages/neo-one-client-common/src/types.ts
packages/neo-one-client-core/src/__tests__/user/DapiUserAccountProvider.test.ts
packages/neo-one-client-core/src/__tests__/user/__snapshots__/DapiUserAccountProvider.test.ts.snap
packages/neo-one-client-core/src/user/Dapi.ts
packages/neo-one-client-core/src/user/DapiUserAccountProvider.ts
packages/neo-one-client-core/src/user/UserAccountProviderBase.ts
packages/neo-one-client-core/src/user/index.ts

Implement DAPIUserAccountProvider in compliance with the the DAPI NEP (https://github.com/neo-project/proposals/pull/69)
Added unit tests similar to those for LocalUserAccountProvider.
#1497

feat(DapiUserAccountProvider): Implement DapiUserAccountProvider

---

renovate.json

This reverts commit 8da351104ad18fd2818ccf011aed8dc3ca6f03af.

Revert "chore(rennovate): add groups back to rennovate"

---

packages/neo-one-node-bin/src/bin/neo-one-node.ts
packages/neo-one-node-bin/src/startNode.ts
packages/neo-one-node-bin/src/utils/getConfiguration.ts

title, the shutdown function to stop the node needed to be bound. Now it doesn't produce an error when `sigInting` the node.

fix(node): fix shutdown process for node-bin

---

scripts/DockerfileNode

Added @neo-one/logger-config to the DockerfileNode so it will be copied and added to the environment.

fix(dockerfilenode): add logger-config to the DockerfileNode

---

actions/dockerhub/entrypoint.sh

fix(dockerhub publish): fix for dockerhub script

---

actions/dockerhub/entrypoint.sh

fix github actions dockerpublsih

---

actions/dockerhub/entrypoint.sh

fix dockeractions

---

actions/dockerhub/entrypoint.sh

dockeractions really fix this time

---

actions/dockerhub/entrypoint.sh

Fix dockeractions.  last one

---

jest/e2e.js
scripts/e2e/jestSetup.js

title. 
see #1660 
also change the source of `setGlobalLogLevel` since its e2e test.

feat(test): add retries to e2e tests

---

packages/neo-one-smart-contract-codegen/src/__tests__/__snapshots__/genCommonFiles.test.ts.snap

fix(tests): update snapshots

---

packages/neo-one-smart-contract-codegen/src/__tests__/__snapshots__/genCommonBrowserFiles.test.ts.snap
packages/neo-one-smart-contract-codegen/src/__tests__/test/__snapshots__/genTest.test.ts.snap

fix(tests): update snapshots again

---

packages/neo-one-http-context/src/context.ts
packages/neo-one-logger/src/loggers.ts
packages/neo-one-logger/src/types.ts
packages/neo-one-node-bin/package.json
packages/neo-one-node-bin/src/__data__/configs/consensus.ts
packages/neo-one-node-bin/src/__data__/configs/index.ts
packages/neo-one-node-bin/src/__data__/getTestKeys.ts
packages/neo-one-node-bin/src/__e2e__/cmd/consensus.test.ts
packages/neo-one-node-blockchain/src/Blockchain.ts
packages/neo-one-node-consensus/src/Consensus.ts
packages/neo-one-node-http-rpc/src/setupRPCServer.ts
packages/neo-one-node-network/src/Network.ts
packages/neo-one-node-protocol/src/Node.ts
packages/neo-one-node-rpc-handler/src/createHandler.ts
packages/neo-one-node-vm/src/execute.ts
packages/neo-one-utils-node/src/createStart.ts
scripts/e2e/One.js
types/e2e.d.ts

add consensus test to `@neo-one/node-bin`.
Also tweak `@neo-one/logger` so that child log levels get set by `setGlobalLogLevels`.

feat(e2e): node-bin e2e consensus test

---

scripts/DockerfileNode
scripts/DockerfileNodeGSUtil

fix(dockerhub): include react-common/static

---

packages/neo-one-website/tutorial/tutorial.md

Updated the tutorial to be consistent with the current version of neo-one

docs(tutorial): update tutorial to reflect neo-one changes

---

packages/neo-one-react-common/src/Tooltip.tsx
packages/neo-one-react-common/src/TooltipBase.tsx

Small fix to properly type TooltipBase

fix(emotion types): remove any typecast for TooltipBase and type properly

---

gulpfile.js

Updated the polyfill for Symbol.asyncIterator for the browserified version of @neo-one/client.
Also fixed how the browserify packages are published.  Previously, all neo-one packages were publishing a browserified version - most of these only contained package.jsons and metadata.  This is because I had overlooked the release commands re-copying package.jsons before publishing.  This PR should fix that.  also made it so `@neo-one/suite-browserify` publishes a working version of neo-one with the client-browserify bundled together with the standard smart-contract packages.  
Discovered the error while making a neo-one app using angular.  The app works with this change and fails to compile without.

build(browserify): update Symbol.asyncIterator fill and add @neo-one/suite-browserify

---

packages/neo-one-website/courses/0-tokenomics/2-launch/0-info/src/ICO.tsx
packages/neo-one-website/courses/0-tokenomics/2-launch/1-balance/src/ICO.tsx
packages/neo-one-website/courses/0-tokenomics/2-launch/2-participate/src/ICO.tsx
packages/neo-one-website/courses/0-tokenomics/2-launch/3-reactive/src/ICO.tsx
packages/neo-one-website/courses/0-tokenomics/2-launch/4-transfer/src/ICO.tsx
packages/neo-one-website/courses/0-tokenomics/2-launch/5-withdraw/src/ICO.tsx
packages/neo-one-website/courses/tsconfig.json

Fixes type error on website courses.

fix(courses): fix type error in courses related to emotion

---

codecov.yml

ignore e2e tests and __data__ folders for tests.

fix(codecov.yml): codecov should ingore __e2e__ tests and __data__ paths

---

.circleci/config.yml

Turning off CI on master-3.x while we get the skeleton of 3.0 working.  As portions become functional we should add back in tests.

ci(temp remove): turn off CI while 3.x is in a broken state

---

common/config/rush/browser-approved-packages.json
common/config/rush/command-line.json
common/config/rush/yarn.lock
packages/neo-one-website/src/components/Header.tsx
packages/neo-one-website/src/components/course/CourseHeader.tsx

WIP on the running the website with Rush. Removed `emotion` component selectors that were causing problems in website build.
Build and run the website. Run Cypress tests.
Still needs work.
Migrating to Rush.
Still needs work.
#1688

fix(website): WIP fixing website with Rush

---

packages/neo-one-build-tools/src/clean.ts

Spencer fix

---

packages/neo-one-website/docs/1-main-concepts/02-smart-contract-basics.md
packages/neo-one-website/docs/1-main-concepts/10-testing.md
packages/neo-one-website/docs/1-main-concepts/12-deployment.md

Added some rough docs on deployment.  Kept intentionally vague until we work with users on the feature.

docs(deploy): update docs on deployment

---

packages/neo-one-website/blog/2019-10-23-neo-one-2-announcement.md

Add blogpost for 2.0 announcement

docs(blog): add blogpost for neo-one 2.0

---

packages/neo-one-website/docs/3-node/1-docker.md
packages/neo-one-website/docs/3-node/2-kubernetes.md
packages/neo-one-website/docs/3-node/3-docker-compose.md
packages/neo-one-website/docs/3-node/4-build-from-source.md
packages/neo-one-website/docs/3-node/5-heroku.md
packages/neo-one-website/docs/3-node/6-configuration.md

docs(node): update node docs

---

packages/neo-one-website/docs/3-node/1-docker.md

docs(node): fix node doc typo

---

packages/neo-one-cli/src/__data__/projects/ico-Js/codegen/client.js
packages/neo-one-cli/src/__data__/projects/ico-Js/codegen/test.js
packages/neo-one-cli/src/__data__/projects/ico-angular/codegen/client.ts
packages/neo-one-cli/src/__data__/projects/ico-angularJs/codegen/client.js
packages/neo-one-cli/src/__data__/projects/ico-vue/codegen/client.ts
packages/neo-one-cli/src/__data__/projects/ico-vueJs/codegen/client.js
packages/neo-one-cli/src/__data__/projects/ico/codegen/client.ts

fixup merge conflict from codegen file that wasn't getting overwritten completely.

fix(rush): fixup e2e test

---

bors.toml

chore(bors): fix bors checks

---

bors.toml

chore(bors): syntax

---

bors.toml

remove deepscan as a bors check

chore(bors): remove deepscan check

---

common/changes/@neo-one/client-common/p2p-models_2019-12-09-20-32.json
common/changes/@neo-one/node-core/p2p-models_2019-12-09-20-32.json
common/changes/@neo-one/node-vm/p2p-models_2019-12-09-20-32.json
common/changes/@neo-one/smart-contract-compiler/p2p-models_2019-12-09-20-32.json
packages/neo-one-build-tools/src/builds/buildBin.ts
packages/neo-one-build-tools/src/builds/buildTypescript.ts
packages/neo-one-client-common/src/IOHelper.ts
packages/neo-one-client-common/src/ScriptBuilder.ts
packages/neo-one-client-common/src/__tests__/ScriptBuilder.test.ts
packages/neo-one-client-common/src/__tests__/models/WitnessScopeModel.test.ts
packages/neo-one-client-common/src/crypto.ts
packages/neo-one-client-common/src/errors.ts
packages/neo-one-client-common/src/models/WitnessScopeModel.ts
packages/neo-one-client-common/src/models/types.ts
packages/neo-one-client-common/src/types.ts
packages/neo-one-node-core/src/Block.ts
packages/neo-one-node-core/src/BlockBase.ts
packages/neo-one-node-core/src/ConsensusData.ts
packages/neo-one-node-core/src/Header.ts
packages/neo-one-node-core/src/constants.ts
packages/neo-one-node-core/src/payload/ConsensusPayload.ts
packages/neo-one-node-core/src/payload/UnsignedConsensusPayload.ts
packages/neo-one-node-core/src/utils/BinaryReader.ts
packages/neo-one-node-vm/src/__tests__/execute.test.ts
packages/neo-one-smart-contract-compiler/src/compile/sb/BaseScriptBuilder.ts

Check-in point for model updates. Block/Transaction changes have been made to the `types` files of `@neo-one/client-common` and several of the errors implicated by this have been addressed.
Also the functions that handle constructing address scripts has been updated. This should close #1878 but I'll leave it open for now.
A lot more is still broken but I think this is a good check point so that we don't work over each other.

P2p models & Address Script Construction

---

packages/neo-one-build-tests/jest/unit.js

quick fix for imports like @neo-one/ec-key

fix(jest): add exception for non-monorepo @neo-one packages

---

packages/neo-one-client-full-common/src/models/contract/ContractModel.ts
packages/neo-one-node-core/src/contract/Contract.ts

one last contract model update

update contract/manifest model

---

packages/neo-one-client-common/src/NativeContract.ts
packages/neo-one-client-common/src/__tests__/NativeContract.test.ts
packages/neo-one-client-common/src/index.ts

Add interface for using NativeContracts in the client.  
Confirm match of the contracts on the blockchain.  Make sure to update this if the name or hash of these contracts change before 3.0 launch.

feat(client): Add NativeContract helpers

---

renovate.json

group all dependency updates into 1 PR

feat(deps): temporarily put renovate updates together

---

renovate.json

feat(deps): remove renovatebot schedule temporarily

---

common/changes/@neo-one/cli/fix-skip_2020-03-22-20-52.json
packages/neo-one-cli/src/build/createTasks.ts

Actually skip neotracker if specified in config.

fix(skip): actually skip neotracker if specified in config

---

common/changes/@neo-one/cli/update-ts-dep_2020-05-04-22-59.json
common/changes/@neo-one/smart-contract-compiler-node/update-ts-dep_2020-05-04-22-59.json
common/changes/@neo-one/smart-contract-compiler/update-ts-dep_2020-05-04-22-59.json
common/changes/@neo-one/smart-contract-typescript-plugin/update-ts-dep_2020-05-04-22-59.json
common/changes/@neo-one/ts-utils/update-ts-dep_2020-05-04-22-59.json
common/changes/@neo-one/typescript-concatenator/update-ts-dep_2020-05-04-22-59.json
common/changes/@neo-one/utils/update-ts-dep_2020-05-04-22-59.json
common/config/rush/common-versions.json
common/config/rush/yarn.lock
packages/neo-one-build-tools-web/package.json
packages/neo-one-build-tools/package.json
packages/neo-one-cli/package.json
packages/neo-one-editor/package.json
packages/neo-one-local-browser/package.json
packages/neo-one-smart-contract-compiler-node/package.json
packages/neo-one-smart-contract-compiler/package.json
packages/neo-one-smart-contract-typescript-plugin/package.json
packages/neo-one-ts-utils/package.json
packages/neo-one-typescript-concatenator/package.json
packages/neo-one-utils/package.json
packages/neo-one-website/package.json
packages/neo-one-website/src/components/Hero.tsx
packages/neo-one-website/src/components/course/courses/CoursesView.tsx
packages/neo-one-website/src/components/home/Home.tsx

Title.
Let CI check it. `rush build` passed locally. `rush tsc` passed locally. `rush test` passed locally, except one failing unit test that is already failing.
Cypress test is expected to fail.
None.
Not using a Release Candidate version anymore.
Unforeseen bugs.

chore(ts): update and unpin typescript dep

---

.vscode/settings.json
common/config/rush/command-line.json
packages/neo-one-build-tools/src/clean.ts
packages/neo-one-editor/src/loaders/packagesLoader.ts

title, this was missed during #2034

fix(web): fix website commands that were using /lib paths still

---

common/changes/@neo-one/cli/nt-dep_2020-06-17-20-21.json

Reverts a minor error in a RushJS change file.

fix(changefile): not a supposed to be a major change

---

common/scripts/neo-one-prune.js
rush.json

fix(rush): add post-install script for pruning neo-one npm dependencies

---

common/scripts/neo-one-prune.js

Title. `fs.rmdir` doesn't support the recursive option in NodeJS v10.X. So this just changes it to handle the file/directory recursion directly.

fix(rush): make neo-one-prune script work with nodejs v10.x

---

.circleci/config.yml

update ci cache for some dependency changes

fix(ci): update ci cache

---

common/changes/@neo-one/cli-common-node/compile-e2e_2020-07-23-22-07.json
common/changes/@neo-one/cli/compile-e2e_2020-07-23-22-07.json
packages/neo-one-cli-common-node/src/configuration.ts
packages/neo-one-cli/src/__e2e__/cmd/compile.test.ts

title, fixup from previous 2 PRs

fix(e2e): fixup compile config for e2e test

---

packages/neo-one-website/blog/2020-07-23-neo-one-2-7-announcement.md
packages/neo-one-website/src/components/content/MainContent.tsx

feat(website): fixup website for release

---

packages/neo-one-website/blog/2020-07-23-neo-one-2-7-announcement.md

Makes minor fixes the latest blog post.
Tested locally. Works.
None.
Links work.
None.
None.

fix(website): minor fixes to blog post

---

packages/neo-one-website/blog/2020-07-23-neo-one-2-7-announcement.md
packages/neo-one-website/docs/0-installation/2-cli.md
packages/neo-one-website/docs/4-contributing/1-codebase-overview.md

Add docs for codebase overview to website.
Looked at it locally and it looks great. Screenshot:
None.
No empty doc page.
None.
#2114 #2007

feat(docs): add docs for codebase overview

---

packages/neo-one-website/docs/2-advanced-guides/09-configuration-options.md

Just updates the website doc on configuration to reflect new compiler options.
None.
None.
Clear docs.
None.
None.

fix(docs): fix config doc

---

packages/neo-one-website/blog/2020-07-23-neo-one-2-7-announcement.md

Change commands.
None.
None.
Better.
None.
None.

fix(website): change yarn install to yarn add

---

common/scripts/install-run-rush.js
common/scripts/install-run.js
rush.json

chore(rush): update rush version

---

packages/neo-one-build-tests/jest/unit.js

Revert Jest setup change that was made while working on `client-core`.

fix(tests): revert jest setup change

---

packages/neo-one-node-core/src/Storage.ts
packages/neo-one-node-core/src/utils/utils.ts
packages/neo-one-node-native/src/KeyBuilder.ts
packages/neo-one-node-native/src/NEOToken.ts
packages/neo-one-node-storage-common/package.json
packages/neo-one-node-storage-common/src/keys.ts
packages/neo-one-node-storage-levelup/src/levelUpStorage.ts
packages/neo-one-node-storage-levelup/src/read.ts

feat(storage): fixup storage.find methods

---

packages/neo-one-node-blockchain/src/Blockchain.ts
packages/neo-one-node-blockchain/src/getNep5UpdateOptions.ts
packages/neo-one-node-core/src/Notification.ts
packages/neo-one-node-core/src/StackItems/StackItems.ts

Fixes how NEP5 balance/transfer storage is updated so that it works.
Tested by running blockchain and seeing balances in storage.
None.
Closer to Neo3.
None.
#2009

fix(nep5): fix nep5 updates

---

packages/neo-one-client-core/src/provider/JSONRPCClient.ts
packages/neo-one-node-core/src/utils/deserializeStackItem.ts
packages/neo-one-node-rpc-handler/src/createHandler.ts

- fix overwritten deserializeStackItem
- update `getrawtransaction` return type in JSONRPCClient
- fix `scriptHashToAddress` method arguments in rpcHandler.

fix(misc): fix overwritten deserializeStackItem, other bug fixes

---

packages/neo-one-node-core/src/utils/deserializeStackItem.ts

fix(node): export deserializeStackItem (woops)

---

packages/neo-one-client-common/src/models/types.ts
packages/neo-one-client-common/src/types.ts
packages/neo-one-client-core/src/provider/JSONRPCClient.ts
packages/neo-one-client-core/src/provider/NEOONEDataProvider.ts
packages/neo-one-client-full-core/src/ReadClient.ts
packages/neo-one-client-full-core/src/types.ts
packages/neo-one-node-rpc-handler/src/createHandler.ts

More bug fixes found while testing JSONRPCClient.

fix(bugs): fix handful of bugs and type errors

---

packages/neo-one-client-common/src/common.ts
packages/neo-one-client-common/src/models/types.ts
packages/neo-one-client-core/src/Hash160.ts
packages/neo-one-client-core/src/__tests__/provider/temp.test.ts
packages/neo-one-client-core/src/provider/JSONRPCClient.ts
packages/neo-one-node-blockchain/src/Blockchain.ts
packages/neo-one-node-rpc-handler/src/createHandler.ts

WIP on testing the `JSONRPCClient` and the RPC methods in the node.

feat(test): JSONRPCClient

---

packages/neo-one-node-blockchain/src/getNep5UpdateOptions.ts

fix(nep5): fix nep5 tracking error

---

common/changes/@neo-one/cli/fix-sp_2020-12-02-20-02.json
common/changes/@neo-one/client-common/fix-sp_2020-12-02-20-02.json
common/changes/@neo-one/client-core/fix-sp_2020-12-02-20-02.json
common/changes/@neo-one/client/fix-sp_2020-12-02-20-02.json
common/changes/@neo-one/smart-contract-codegen/fix-sp_2020-12-02-20-02.json
packages/neo-one-cli/src/__data__/projects/exchange/codegen/client.ts
packages/neo-one-cli/src/__data__/projects/ico-Js/codegen/client.js
packages/neo-one-cli/src/__data__/projects/ico-angular/codegen/client.ts
packages/neo-one-cli/src/__data__/projects/ico-angularJs/codegen/client.js
packages/neo-one-cli/src/__data__/projects/ico-vue/codegen/client.ts
packages/neo-one-cli/src/__data__/projects/ico-vueJs/codegen/client.js
packages/neo-one-cli/src/__data__/projects/ico/codegen/client.ts
packages/neo-one-client-common/src/crypto.ts
packages/neo-one-client-core/package.json
packages/neo-one-client-core/src/clientUtils.ts
packages/neo-one-client-core/src/index.ts
packages/neo-one-client/src/index.ts
packages/neo-one-smart-contract-codegen/src/__tests__/__snapshots__/genCommonBrowserFiles.test.ts.snap
packages/neo-one-smart-contract-codegen/src/__tests__/__snapshots__/genCommonFiles.test.ts.snap
packages/neo-one-smart-contract-codegen/src/__tests__/client/__snapshots__/genBrowserClient.test.ts.snap
packages/neo-one-smart-contract-codegen/src/__tests__/client/__snapshots__/genClient.test.ts.snap
packages/neo-one-smart-contract-codegen/src/client/genBrowserClient.ts
packages/neo-one-smart-contract-codegen/src/client/genClient.ts

Reverts most of #2056.
None.
See #2056
Client setup will work in browser environment again.
Reopens issue #1997
#2171 
#2229

fix(client): remove synchronized-promise and fix process in browser

---

common/changes/@neo-one/cli/fixup-cli_2020-12-08-19-02.json
common/changes/@neo-one/client-core/fixup-cli_2020-12-08-19-02.json
packages/neo-one-cli/src/cmd/start/index.ts
packages/neo-one-cli/src/cmd/start/network.ts
packages/neo-one-cli/src/cmd/stop/index.ts
packages/neo-one-client-core/src/__tests__/user/LocalUserAccountProvider.test.ts

title, fixup CLI command. preparing for release.

feat(cli): fixup cli start network command

---

packages/neo-one-node-vm/src/Methods/EngineMethods.ts
packages/neo-one-node-vm/src/__tests__/Dispatcher.test.ts

Preview4 blockchain changes (#2284)

---

packages/neo-one-build-tools/src/formats.ts
packages/neo-one-cli-common/src/deployContract.ts
packages/neo-one-client-common/src/ScriptBuilder.ts
packages/neo-one-client-core/src/args.ts
packages/neo-one-client-full-core/src/user/LocalUserAccountProvider.ts
packages/neo-one-node-blockchain/src/Blockchain.ts
packages/neo-one-node-storage-levelup/src/levelUpStorage.ts
packages/neo-one-node-vm/package.json
packages/neo-one-smart-contract-compiler/src/__tests__/compile/builtins/contract/scriptBuilder.test.ts

Adds minor fixes, primarily to the Node and CLI, to get make functionality working, like `yarn neo-one start network` and `yarn neo-one build`.
Tested manually locally.
None.
Bug fixes and CLI and node working properly. Closer to Neo3.
None.
#2272

fix(preview4): minor fixes to the node and others for preview4

---

packages/neo-one-cli/src/__data__/projects/exchange/codegen/client.ts
packages/neo-one-cli/src/__data__/projects/ico-Js/codegen/client.js
packages/neo-one-cli/src/__data__/projects/ico-angular/codegen/client.ts
packages/neo-one-cli/src/__e2e__/cmd/init.test.ts

Fix e2e test from previous change to CLI `init` command.
Tested the e2e test locally. Passes.
None.
Tests passing.
None.
None.

fix(e2e): fix init test for cli

---

.all-contributorsrc
README.md
packages/neo-one-website/docs/0-installation/2-cli.md

Updates our `all-contributors` file and the all-contributors table in our README.
Just doc changes. Review them locally. Will be confirmed on deploy.
None.
Better docs. Contributors updated.
None.

feat(docs): update all-contributors and CLI docs

---

packages/neo-one-website/src/components/Footer.tsx

Update footer links.
None.
None.
Updated links.
None.
None.

feat(website): update footer links

---

packages/neo-one-website/docs/3-node/4-build-from-source.md

Update docs for running NEO•ONE node from source.
None.
None.
Better docs. Accurate.
None.
None.

fix(docs): update docs on building node from source

---

packages/neo-one-website/docs/3-node/4-build-from-source.md

Updates doc on RC file to be clearer.
None.
None.
Clearer docs.
None.
None.

fix(docs): cleanup node source docs

---

packages/neo-one-website/docs/0-installation/5-contract-mixins.md

contract mixin fix.
npm `install` instead of npm `add`
N/A
N/A
N/A
N/A
N/A

fix(doc): contract mixin

---

packages/neo-one-node-blockchain/src/Blockchain.ts
packages/neo-one-node-rpc-handler/src/createHandler.ts
packages/neo-one-website/blog/2021-03-18-neo-one-preview5-announcement.md
packages/neo-one-website/docs/0-installation/5-contract-mixins.md

Adds blog post for Preview5 release. Other minor fixes.
Manually.
None.
Blog post. Bug fixes.
None.
None.

feat(blog): preview5 blog post plus minor fixes

---

common/config/rush/command-line.json
packages/neo-one-smart-contract/src/index.d.ts
packages/neo-one-website/src/components/home/Home.tsx
packages/neo-one-website/src/loaders/coursesLoader.ts

Minor updates to get the N3 version of the website published at n3.neo-one.io, a WIP version.
n3.neo-one.io
None.
Some documentation for N3 work somewhere, just a start.
None.
#2388

fix(website): publish n3 version of website

---

packages/neo-one-smart-contract-compiler/src/__tests__/compile/builtins/contract/mapStorage.test.ts
packages/neo-one-smart-contract-compiler/src/compile/helper/contract/InvocationIsCallerHelper.ts
packages/neo-one-smart-contract-compiler/src/compile/helper/storage/CacheStorageHelper.ts
packages/neo-one-smart-contract-compiler/src/compile/helper/storage/CommonStorageHelper.ts
packages/neo-one-smart-contract-compiler/src/compile/helper/storage/DeleteCacheStorageHelper.ts

- Removes hard-coded triggertype references in the compiler
None.
None.
No more number mismatches in compiler.
None.
#2388

fix(compiler): fix triggertype references in compiler

---

packages/neo-one-client-common/src/Instruction.ts
packages/neo-one-smart-contract-compiler/src/compile/builtins/contract/blockchain.ts
packages/neo-one-smart-contract-compiler/src/compile/helper/contract/IsCallerHelper.ts

- Fix we check for "undefined" when getting blockchain objects.
- Remove empty operand check for `Instruction`.
- `blockchain.test.ts` in compiler
None.
Accurate blockchain APIs.
None.
#2388

fix(compiler): fix null/undefined checks and instruction check

---

packages/neo-one-website/tutorial/tutorial.md

- Updates tutorial page to match `master-2.x` branch, which adds and extra setup step for clarity.
None.
None.
Clarity.
None.

fix(tutorial): update tutorial

---

packages/neo-one-cli-common/src/deployContract.ts
packages/neo-one-cli/src/build/deployContract.ts
packages/neo-one-cli/src/compile/writeContract.ts
packages/neo-one-client-switch/src/common/processError.ts
packages/neo-one-client-switch/src/common/processTrace.ts
packages/neo-one-node-core/src/manifest/ContractPermission.ts
packages/neo-one-node-vm/lib/Dispatcher.csproj
packages/neo-one-smart-contract-codegen/src/types/genFunctionParameters.ts
packages/neo-one-smart-contract-compiler/src/utils/processMethods.ts
packages/neo-one-smart-contract-test-common/src/withContracts.ts

- Minor fixes for using the CLI to compile, build, and test smart contracts with NEO•ONE for RC1
- Update .csproj with latest version numbers (still contains local file paths though for devs)
- Temporary fixes for sourceMap issues with Jest
- `yarn neo-one compile`
- `yarn neo-one build`
- `yarn neo-one generate`
- `yarn test`
In a demo repo using NEO•ONE.
None.
Major/minor bug fixes in codegen, node, client, CLI for using NEO•ONE.
None.
#2388

fix(client): fix bugs in client, node, cli for rc1

---

packages/neo-one-node-protocol/src/Message.ts
packages/neo-one-node-protocol/src/Node.ts

Update NEO•ONE node user agent.
None.
None.
UA updated.
None.
#2410

fix(node): update node UA

---

packages/neo-one-cli/src/cmd/start/writePidFile.ts

Fix problem with later NodeJS versions not starting network.
Tested locally with newest NodeJS version. Works.
None.
Node starts locally in newer NodeJS versions.
None.
#2287

fix(cli): fix writePidFile

---

packages/neo-one-node-network/src/Network.ts
packages/neo-one-node-vm/lib/Dispatcher.csproj

- Add small optimization to node startup when connecting to peers.
- Change Dispatcher CSPROJ to use published instead of local C# packages.
None.
None.
Slightly faster node network startup.
None.
#2410

feat(node): add small network optimization

---

packages/neo-one-website/tutorial/tutorial.md

- Remove courses mentions from tutorial in N3 docs.
None.
None.
Clearer docs.
None.
#2410

feat(docs): remove course mentions from tutorial

---

packages/neo-one-smart-contract-compiler/src/compile/getSmartContractInfo.ts
packages/neo-one-smart-contract-compiler/src/contract/DebugInfoProcessor.ts

feat(cli): update debugger output for v1.2 of neo debug spec #2

---

packages/neo-one-node-consensus/src/__data__/context.ts
packages/neo-one-node-consensus/src/context/common.ts
packages/neo-one-node-core/src/consensus/ConsensusContext.ts
packages/neo-one-node-native/src/LedgerContract.ts
packages/neo-one-smart-contract-compiler/src/compile/builtins/contract/address/index.ts
packages/neo-one-smart-contract/src/index.d.ts

Add more native contract Address APIs available in compiler. Plus a few type error fixes.
None.
None.
Addresses available in SCs.
None.
#2484
#2410

fix(compiler): add addresses to address api

---

packages/neo-one-client-full-common/src/__data__/models.ts
packages/neo-one-client-full-common/src/__tests__/models/__snapshots__/ContractManifestModel.test.ts.snap

No requirement
Fixed unit test data model in order to match the accepted type
```sh
rush test -t packages/neo-one-client-full-common/src/__data__/models.ts
```
-
Unit test validation
No side-effect
#2479

fix(client): fix trusts types through client and compiler (#2479)

---

packages/neo-one-website/blog/2021-07-02-neo-one-rc3-announcement.md

- Add blog post for RC3 release
https://n3.neo-one.io/blog/2021/03/18/neo-one-rc3-announcement
None.
Announcement.
None.
#2410

feat(website): add rc3 blog post

---

packages/neo-one-website/docs/0-installation/0-quick-start.md
packages/neo-one-website/docs/0-installation/2-environment-setup.md
packages/neo-one-website/docs/3-node/4-build-from-source.md
packages/neo-one-website/tutorial/tutorial.md

- Fixes incorrect path for edge_app_root
None.
None.
Correct docs.
None.
#2410

fix(docs): fix edge_app_root documentation

---

packages/neo-one-client-common/src/Script.ts
packages/neo-one-node-core/src/StackItems/PointerStackItem.ts

I implemented the Script class a while back which can now be used in the PointerStackItem.
None.
None.
Closer to N3.
None.
#2410

fix(node): add script class to pointer

---

.vscode/settings.json

I added another rule to the VS Code settings to fix a performance issue on Windows (it was consuming 100% CPU)
I reopened VS Code and I don't have that issue anymore

Fixing search on Windows machines

---

packages/neo-one-node-vm/lib/Dispatcher.csproj

- Updates/fixes CSPROJ with deployed Neo and NeoVM forks.
Deployment.
None.
RC4
None.
#2521

feat(rc4): update csproj for rc4 deployment

---

packages/neo-one-cli/src/cmd/start/network.ts
packages/neo-one-node-blockchain/src/Blockchain.ts
packages/neo-one-node-neo-settings/src/createMain.ts
packages/neo-one-node-neo-settings/src/createPriv.ts
packages/neo-one-node-neo-settings/src/createTest.ts
packages/neo-one-node-vm/src/utils.ts
packages/neo-one-smart-contract-test/src/createNode.ts

- Fix how standby committee and standby validators are created
- Update how "int"s are validated in VM settings
- Fix initial gas distribution parsing
- Update default testnet validators
- Update TestNet network number
- Deployed to staging cluster
None
Cleanup settings
None
#2521

fix(node): fix how settings are created

---

packages/neo-one-node-core/src/Header.ts
packages/neo-one-node-core/src/transaction/Transaction.ts
packages/neo-one-node-native/src/methods/gasTokenMethods.ts
packages/neo-one-node-neo-settings/src/createMain.ts

Updates for N3 MainNet 3.0.2.
Deploy and sync with current TestNet at some point later.
None.
MainNet.
None.
#2529

feat(mainnet): make n3 mainnet updates

---

common/changes/@neo-one/node-blockchain/gas-stop_2021-09-14-06-03.json
common/changes/@neo-one/node-core/gas-stop_2021-09-14-06-03.json
common/changes/@neo-one/node-neo-settings/gas-stop_2021-09-14-06-03.json
packages/neo-one-node-blockchain/src/Blockchain.ts
packages/neo-one-node-blockchain/src/__data__/settings.ts
packages/neo-one-node-core/src/Settings.ts
packages/neo-one-node-core/src/utils/utils.ts
packages/neo-one-node-neo-settings/src/common.ts
packages/neo-one-node-neo-settings/src/createMain.ts
packages/neo-one-node-neo-settings/src/createTest.ts
packages/neo-one-node-neo-settings/src/serde.ts
packages/neo-one-website/docs/3-node/6-configuration.md

- Update neo2 implementation to stop GAS claims at block 8,000,000
Push to production.
None.
Consistent with Neo2.
None.
None.

feat(n3): stop gas generation at block 8M

---

.github/workflows/dockerhub.yaml

- Add master-2.x branch to Docker workflow.
None.
None.
Docker builds on 2.x branch.
None.
None.

fix(nits): fix dockerhub workflow

---

common/config/rush/browser-approved-packages.json
common/config/rush/yarn.lock

- Updates yarn.lock and approved-packages.json from last commit.
None.
None.
Updates.
None.
None.

fix(nits): update yarnlock and common

---

common/changes/@neo-one/client-common/node-fixes_2021-10-24-22-56.json
common/changes/@neo-one/client-core/add-debug_2021-11-03-22-23.json
common/changes/@neo-one/node-blockchain/add-debug_2021-11-03-22-23.json
common/changes/@neo-one/node-core/node-fixes_2021-10-24-22-56.json
common/changes/@neo-one/node-neo-settings/add-debug_2021-11-03-22-23.json
common/changes/@neo-one/node-protocol/node-fixes_2021-10-24-22-56.json
common/changes/@neo-one/node-rpc-handler/node-fixes_2021-10-24-22-56.json
packages/neo-one-client-core/src/provider/JSONRPCClient.ts
packages/neo-one-client-core/src/provider/NEOONEDataProvider.ts
packages/neo-one-node-blockchain/src/Blockchain.ts
packages/neo-one-node-neo-settings/src/createMain.ts
packages/neo-one-node-neo-settings/src/createPriv.ts
packages/neo-one-node-neo-settings/src/createTest.ts

- Update config settings
- Add changelogs
- Add audit script in blockchain class
None.
None.
Minor fixes.
None.
None.

add node sync audit func and minor updates

---

packages/neo-one-node-blockchain/package.json
packages/neo-one-node-blockchain/src/Blockchain.ts

Adds new audit script for careful auditing of our node while syncing.
Used it to audit/sync a node.
None.
Ability to audit sync results.
None.
None.

feat: add new audit script
