- packages/neo-one-cli/package.json
- packages/neo-one-cli/src/InteractiveCLI.js
- packages/neo-one-cli/src/interactive/createCRUD.js
- packages/neo-one-server-plugin/src/types.js
- yarn.lock
Previously, delete prompt only worked in interactive cli and hung when delete command passed as an argument (e.g. neo-one delete net altest).  Now the prompt works the same in both cases.
Tested delete command and all prompt options in both interactive and as an argument.
Prompts in both use cases
#20
> Delete prompt now works as argument from cli

- packages/neo-one-server-plugin-wallet/src/crud/smartContract/CreateSmartContractCRUD.js
- packages/neo-one-server-plugin-wallet/src/crud/wallet/common.js
Wallet password prompt & smart contract creation prompt now work as arguments from the cli.  The change was to use inquirer.js instead of vorpal's prompt method.
Did not.
Related to #20
> All prompts now work as arguments from the cli

- packages/neo-one-smart-contract-compiler/src/__tests__/compile/expression/BinaryExpressionCompiler.test.ts
- packages/neo-one-smart-contract-compiler/src/compile/expression/BinaryExpressionCompiler.ts
- packages/neo-one-smart-contract-compiler/src/transpile/transpiler/NEOTranspiler.ts
Resolve #144
BinaryExpressionCompiler.ts
+ code for instanceOf
BinaryExpressionCompiler.ts
+ test for instanceof
Code Cleanup on NEOTranspiler.ts
- Removed an unused import of: ParameterDeclaration
add functionality that supports instanceof in BinaryExpressionCompiler 
Tested with an execution with by creating a class and creating an instance of this class.  
Then testing that instanceof returned the expected value.
none, this collaborative effort with @dicarlo2 and we went with the standard solution.
the ability to use instanceof 
none expected.
This resolves Issue #144: Support `instanceof` keyword (BinaryExpressionCompiler.ts)
> #144 - Support 'instanceof keyword in BinaryExpressionCompiler.ts

- packages/neo-one-client-core/src/index.d.ts
- packages/neo-one-smart-contract-compiler/src/compile/syscalls.ts
Addresses card#178 
Reviewed similar syscalls; current solution is based off Neo.Blockchain.GetTransacitonType
Added Entry in index.d.ts
Submitted for peer review 
DO NOT MERGE
> Add syscall: Neo.Blockchain.getTransactionHeight

- packages/neo-one-monitor/src/Reporter.ts
- packages/neo-one-monitor/src/__tests__/__snapshots__/BrowserMonitor.test.ts.snap
Add header to Reporter of content-type: application/json so that the quest is received in the proper format at the endpoint.
> Add content-type header to Reporter fetch

- packages/neo-one-monitor/src/CollectingMetricsFactory.ts
- packages/neo-one-monitor/src/MetricsFactoryProxy.ts
- packages/neo-one-monitor/src/ReportHandler.ts
- packages/neo-one-monitor/src/__tests__/BrowserMonitor.test.ts
- packages/neo-one-monitor/src/types.ts
Previously, ReportHandler kept track of which metrics it had forwarded to the NodeMetricsFactory.  This caused issues where in some cases the NodeMetricsFactory had already registered some of those metrics with prometheus.  Now, the MetricsFactoryProxy keeps track of all metrics which have been registered, so there should be no issue when forwarding metrics from the browser.
> Keep track of metrics in MetricsFactoryProxy

- packages/neo-one-client/src/__tests__/user/LocalUserAccountProvider.test.ts
- packages/neo-one-client/src/__tests__/user/__snapshots__/LocalUserAccountProvider.test.ts.snap
- packages/neo-one-client/src/errors.ts
- packages/neo-one-client/src/provider/neoone/NEOONEProvider.ts
- packages/neo-one-client/src/user/LocalUserAccountProvider.ts
Added a mutable Set to localUserAccountProvider that stores user-inputs/block-index so that a user cannot attempt to use the same inputs across 2 (or more) unique transfers. See the bottom of LocalUserAccountProvider.test.ts for some insight on to what this is catching exactly.
Resolves #211
> Add bug fix for attempting multiple inputs on the same block

- packages/neo-one-client/src/Client.ts
- packages/neo-one-client/src/__tests__/Client.test.ts
- packages/neo-one-client/src/__tests__/__snapshots__/Client.test.ts.snap
- packages/neo-one-client/src/__tests__/args.test.ts
- packages/neo-one-client/src/args.ts
- packages/neo-one-client/src/types.ts
Adds client argument assertion checks.
Wrote and implement additional assertions for ~all arguments of public Client.ts methods. Wrote additional pass/fail tests in args.test.ts, as well as updating tests in Client.test.ts because they were built on the premise that they can pass anything into argument fields. 
Passing all tests currently.
Addresses issue #43
> Adds client argument assertion checks

- packages/neo-one-client-core/src/transaction/ClaimTransaction.ts
- packages/neo-one-client-core/src/transaction/ContractTransaction.ts
- packages/neo-one-client-core/src/transaction/EnrollmentTransaction.ts
- packages/neo-one-client-core/src/transaction/Input.ts
- packages/neo-one-client-core/src/transaction/InvocationTransaction.ts
- packages/neo-one-client-core/src/transaction/IssueTransaction.ts
- packages/neo-one-client-core/src/transaction/MinerTransaction.ts
- packages/neo-one-client-core/src/transaction/Output.ts
- packages/neo-one-client-core/src/transaction/PublishTransaction.ts
- packages/neo-one-client-core/src/transaction/RegisterTransaction.ts
- packages/neo-one-client-core/src/transaction/StateTransaction.ts
- packages/neo-one-client/src/DeveloperClient.ts
- packages/neo-one-client/src/__tests__/user/LocalUserAccountProvider.test.ts
- packages/neo-one-client/src/__tests__/user/__snapshots__/LocalUserAccountProvider.test.ts.snap
- packages/neo-one-client/src/types.ts
- packages/neo-one-client/src/user/LocalUserAccountProvider.ts
Working currently in tests. Consolidates unspent outputs when a byte-limit is specified on the keystore to avoid running into the problem of not being able to make a large transaction with multiple small inputs because of ledger/wallet restrictions.
I'm pretty confident in the process and have a test for contractTransaction and claimTransaction that both pass with / without network fees and variable byteLimits.
edit: fixed red squiggles.
> Adds Unspent Output Consolidation #221

- packages/neo-one-smart-contract-compiler/src/__tests__/compile/syscalls.test.ts
- packages/neo-one-smart-contract-compiler/src/compile/syscalls.ts
- packages/neo-one-smart-contract/src/index.d.ts
Add support for Neo.Runtime.Call
Add Test for Neo.Runtime.Call 
Additional updates for allowing generateTypes.ts to run after JS to TS conversion.
> Enable syscall: Neo.Runtime.Call

- .gitignore
- packages/neo-one-client-core/src/crypto/crypto.ts
- packages/neo-one-client-core/src/utils/utils.ts
- packages/neo-one-server-plugin-wallet/src/__data__/bootstrapTestUtils.ts
- scripts/e2e/One.js
- scripts/e2e/jestSetup.js
removes `import * as crypto from 'crypto'` from some places of client-core which caused a deprecation warning to trigger even though we never used the deprecated modules.
> fixes build errors

- .circleci/config.yml
- codecov.yml
- jest/e2e.js
- jest/unit.js
- package.json
- yarn.lock
We now use `nyc` and to generate code coverage reports. This is initial testing but it seems pretty plug and play. 
```bash
#collects coverage results while testing
yarn nyc --clean <any jest test> --coverage
#logs out the most recent coverage report
yarn nyc report
#sends the coverage results to codecov.io
yarn report-coverage --token=<codecoverage token>
```
running these you should see code coverage reports for the given test.
I've added `nyc` to `package.json` as well as `codecov`. 
in CI we add:
```
yarn nyc --clean --cache yarn e2e-ci (CI stuff...) --coverage
yarn report-coverage
```
If we want to add more tests it is import to use nyc --clean before each test so that we have a clean coverage directory.
Code coverage is SICK.
Sometimes CI isn't uploading the full coverage report? …
> adds code coverage reports and support for codecov.io

- README.md
appveyor badge used to just link to the image of the badge. Now it properly links to the latest build result.
apart from fixing the badge link, I also properly segmented the badges on the readme so they aren't clumped together in one line like only a MANIAC would do.
This change has potential to change everything about this project.
> fixes appveyor badge link

- jest/ledger.js
- package.json
- packages/neo-one-client-core/src/__ledger_tests__/LedgerHandler.test.ts
- packages/neo-one-client-core/src/__tests__/user/keystore/LedgerKeyStore.test.ts
- packages/neo-one-client-core/src/__tests__/user/keystore/__snapshots__/LedgerKeyStore.test.ts.snap
- packages/neo-one-client-core/src/errors.ts
- packages/neo-one-client-core/src/user/keystore/LedgerHandler.ts
- packages/neo-one-client-core/src/user/keystore/LedgerKeyStore.ts
- packages/neo-one-client-switch/package.json
- packages/neo-one-client-switch/src/browser/LedgerTransport.ts
- packages/neo-one-client-switch/src/browser/index.ts
- packages/neo-one-client-switch/src/common/Ledger.ts
- packages/neo-one-client-switch/src/common/index.ts
- packages/neo-one-client-switch/src/index.browser.ts
- packages/neo-one-client-switch/src/index.ts
- packages/neo-one-client-switch/src/node/LedgerTransport.ts
- packages/neo-one-client-switch/src/node/index.ts
- yarn.lock
#192 
(resubmission of #403 after refactoring of neo-one)
Strap in for this commit boys. L E D G E R support is here!
In this commit I've done a few things:
1) created declaration files for external ledger packages in our `@types` directory.
2) created a browser/node switchable `LedgerTransport` in `@neo-one/client-switch` which handles communicating with our Ledgers in their respective environments.
3) created `LedgerKeyStore` in `@neo-one/client/user/keystores/` which implements the KeyStore interface (modified to fit some functions that aren't necessary for ledger) using our newly defined `LedgerHandler` to handle the passing of messages and connections to ledgers.
4) ??? hopefully this just hooks up super ez-pz?
5) profit.
we add two new dependencies to `@neo-one/client-switch`, …
> Ledger Support for Node and Browser

- packages/neo-one-editor/src/monaco/AsyncLanguageService.ts
- packages/neo-one-editor/src/monaco/features/FormatAdapter.ts
- packages/neo-one-editor/src/monaco/features/FormatOnTypeAdapter.ts
- packages/neo-one-editor/src/monaco/features/utils.ts
Moved `convertFormattingOptions` method from utils to the ts worker.  Updated 2 locations where the method was used.
> move typescript to worker only

- packages/neo-one-website/src/components/tutorial/Tutorial.tsx
Changed the scroll sync to use nearest position instead of currently in view to determine the currently selected section.
> Fix scroll sync to use nearest position vs. inview

- packages/neo-one-website/src/components/course/lesson/LessonView.tsx
- packages/neo-one-website/src/elements/Markdown.tsx
Links on markdown pages now open in new page.  The exception are same-page links which will still just scroll you to the section (e.g. #section3).
> Markdown links open new page

- jest/base.js
- packages/neo-one-smart-contract-compiler/src/__tests__/compile/helper/contract/InvokeSmartContractHelper6.test.ts
somehow I snuck in a `test.only` to InvokeSmartContractHelper6. Also I brought the diagnostic fileName in line with the other ones, don't know why it wasn't originally.
Sorry for missing these initially.
My wallaby was straight broken with that `test.only`. It was only running that one test. weird :thinking:
> fixes a .only that shouldn't be and formats a filename in base.js

- packages/neo-one-developer-tools-frame/src/NetworkSelector.tsx
- packages/neo-one-developer-tools-frame/src/ToolbarSelector.tsx
- packages/neo-one-developer-tools-frame/src/TransferAmount.tsx
- packages/neo-one-developer-tools-frame/src/WalletSelectorBase.tsx
- packages/neo-one-react-common/package.json
- packages/neo-one-react-common/src/Select.tsx
- packages/neo-one-react-common/src/index.ts
Moved our react-select based Select into @neo-one/react-common so it is exposed and can be use by others.
> Move Select to be exposed by react-common

- packages/neo-one-node-bin/package.json
- packages/neo-one-node-bin/src/bin/neo-one-node.ts
- packages/neo-one-node-bin/src/createMonitor.ts
- packages/neo-one-node-bin/src/index.ts
- packages/neo-one-node-bin/src/startNode.ts
Adds `@neo-one/node-bin`, which acts as the entry point for `@neo-one/node`. Creates some helper setup functions to prepared for more detailed configuration options.
```bash
yarn build:e2e
node ./dist/neo-one/packages/neo-one-node-bin/bin/neo-one-node
```
Rip this thing apart if it doesn't look how you think it should. I want it to be the best it can be.
Woah node entrypoint
I had the create a folder for it to put its data, right now that is `neo-one-node/data`, there is almost certainly a better place/ way for me to handle this folder, should that come in the next commit? I temp added the data folder to `.gitignore`.
#708
> feat(node): add @neo-one/node-bin

- package.json
- yarn.lock
Revert tslint-microsoft-contrib dependency to 5.2.1 before 6.0 where a bug was introduced that incorrectly flags our ` index.ts ` files with single export-defaults entries as failing the export-name test. 
reverting tslint-microsoft-contrib until next release.
> fix(tslint-export-name): revert to "tslint-microsoft-contrib": "5.2.1"

- packages/neo-one-smart-contract-compiler/src/compile/builtins/contract/crypto.ts
- packages/neo-one-smart-contract/src/index.d.ts
The order in which same-named items are parsed matters for dgeni. This ordering preserves all the
data we need.
#702
> docs(Reference): Rearrange sc doc file for better dgeni parsing.

- packages/neo-one-react-common/src/Selector.tsx
update Selector.tsx to fix undefined event style assertion, this is related to the style updates provided by PR #758
provide type for parameter 'event'
https://github.com/neo-one-suite/neo-one/pull/758 see this failing test https://circleci.com/gh/neo-one-suite/neo-one/25308?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
> style(neo-one-react-common): update to comply with styled dep update

- package.json
- yarn.lock
Revert "chore(deps): update dependency @reactivex/ix-esnext-esm to v2.4.3"
Pull request https://github.com/neo-one-suite/neo-one/pull/904 containing commit `d6cc1b1ce80b3b7e81c8fec85586857773f194bc` breaks the `compileTypescript:es2017:cjs:task`
Reverting this change results in a successful build:
yarn && yarn build 
Build is no longer broken
> chore(dep): revert ix-esnext-esm from 2.4.3 to 2.3.5

- packages/neo-one-node-network/src/Network.ts
- packages/neo-one-node-protocol/src/Node.ts
Adjust log-levels of some commands in the node to make `info`, `verbose`, and `debug` more distinct in what they log for easier use.
Could be better ways to organize them maybe?
readability of node-monitor output.
> fix(node): adjust logging levels of several node commands.

- package.json
- yarn.lock
Revert latest commit f4af6ee81ea8ca3904b4b46cd7086c98e6c6e794 the 2.5 update of `ix-esnext-esm` contains an issue that matches an open issue ReactiveX/IxJS has accepted onto their backlog. (1) This issue has been observed in releases after 2.3.5.
(1) https://github.com/ReactiveX/IxJS/issues/236
@ v = 2.3.5 our source does not produce these errors.
@ v > 2.3.5 we perform:
const iterable = AsyncIterableX.from(this.enumerator as AsyncIterableIterator<Value>).pipe(map(({ value }) => ({ value })),
);
yarn install
yarn build
build is no longer broken.
* https://github.com/neo-one-suite/neo-one/pull/936
* https://github.com/neo-one-suite/neo-one/pull/904
> chore(deps): revert dependency @reactivex/ix-esnext-esm to v2.3.5

- package.json
- packages/neo-one-react-core/package.json
- packages/neo-one-website/courses/0-tokenomics/2-launch/0-info/package.json
- packages/neo-one-website/courses/0-tokenomics/2-launch/1-balance/package.json
- packages/neo-one-website/courses/0-tokenomics/2-launch/2-participate/package.json
- packages/neo-one-website/courses/0-tokenomics/2-launch/3-reactive/package.json
- packages/neo-one-website/courses/0-tokenomics/2-launch/4-transfer/package.json
- packages/neo-one-website/courses/0-tokenomics/2-launch/5-withdraw/package.json
- packages/neo-one-website/src/components/reference/ReferenceGrid.tsx
- yarn.lock
Do #758 but also add a type to an inferred any callback.
```
yarn tsc
```
#758
> chore(deps): update dependency @types/styled-components to v4.1.6

- packages/neo-one-client-common/src/crypto.ts
I incorrectly reverted my own types to "fix" a lint issue, but I actually just made a mistake and the issue was our usage not the type definition. When that definition change is pushed this will fix it.
The type PR is here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/32447#pullrequestreview-196229199
Essentially typing it as `string` worked because the underlying js used the correct overload for `Buffer.from(...)` even though typescript said we were using the string overload.
I thought this was going to fail until the DT PR came in but that isn't the case so we could merge now and then the DT change won't affect anything.
> fix(types): adjust 'scrypt-js' callback usage

- packages/neo-one-client-core/package.json
- packages/neo-one-client-full-core/package.json
- packages/neo-one-node-consensus/package.json
- packages/neo-one-node-vm/package.json
Update ReactiveX dependencies so build finishes successfully.
Downgrade and pin reactivex dependencies to 2.3.5
yarn build
Determine why variable inference is not working on the static `from` function.
We can build successfully.
Pinned to a dependency requires human intervention to upgrade.
> fix(reactivex): downgrade and pin reactivex dependencies

- packages/neo-one-cli/src/InteractiveCLI.ts
- packages/neo-one-cli/src/utils/reportError.ts
report server log path and last N lines when server fails to start
Update start-server error-handling to also report last N lines of server log & path of log.
run tests
Provide additional hints when debugging in the local development environment.
Sample Output:
> feat(neo-one-cli): print last N lines of server log when server fails to start

- packages/neo-one-local-browser/src/build/build.ts
- packages/neo-one-server-plugin-project/src/build/generateCommonCode.ts
- packages/neo-one-server-plugin-project/src/types.ts
- packages/neo-one-server-plugin-project/src/utils/paths.ts
- packages/neo-one-smart-contract-codegen/src/__tests__/__snapshots__/genCommonBrowserFiles.test.ts.snap
- packages/neo-one-smart-contract-codegen/src/__tests__/__snapshots__/genCommonFiles.test.ts.snap
- packages/neo-one-smart-contract-codegen/src/__tests__/angular/__snapshots__/genAngular.test.ts.snap
- packages/neo-one-smart-contract-codegen/src/__tests__/angular/genAngular.test.ts
- packages/neo-one-smart-contract-codegen/src/__tests__/client/__snapshots__/genBrowserClient.test.ts.snap
- packages/neo-one-smart-contract-codegen/src/__tests__/client/__snapshots__/genClient.test.ts.snap
- packages/neo-one-smart-contract-codegen/src/__tests__/genCommonBrowserFiles.test.ts
- packages/neo-one-smart-contract-codegen/src/__tests__/genCommonFiles.test.ts
- packages/neo-one-smart-contract-codegen/src/__tests__/generated/__snapshots__/genGenerated.test.ts.snap
- packages/neo-one-smart-contract-codegen/src/__tests__/vue/__snapshots__/genVue.test.ts.snap
- packages/neo-one-smart-contract-codegen/src/__tests__/vue/genVue.test.ts
- packages/neo-one-smart-contract-codegen/src/angular/genAngular.ts
- packages/neo-one-smart-contract-codegen/src/angular/index.ts
- packages/neo-one-smart-contract-codegen/src/client/genBrowserClient.ts
- packages/neo-one-smart-contract-codegen/src/client/genClient.ts
- packages/neo-one-smart-contract-codegen/src/genCommonBrowserFiles.ts
- packages/neo-one-smart-contract-codegen/src/genCommonFiles.ts
- packages/neo-one-smart-contract-codegen/src/generated/genGenerated.ts
- packages/neo-one-smart-contract-codegen/src/vue/genVue.ts
- packages/neo-one-smart-contract-codegen/src/vue/index.ts
Add code-gen for angular and vue to provide access to smart contract and client methods in an angular or vue project. 
#718, #719
> feat(angular): Add code-gen for angular.

- gulpfile.js
- package.json
- packages/neo-one-client-common/package.json
- packages/neo-one-client-core/package.json
- packages/neo-one-client-full-core/package.json
- packages/neo-one-editor-server/src/entry.ts
- packages/neo-one-editor-server/src/lambda.ts
- packages/neo-one-local-browser/src/utils.ts
- packages/neo-one-local/src/setupWallets.ts
- packages/neo-one-monitor/src/NodeMonitor.ts
- packages/neo-one-node-blockchain/package.json
- packages/neo-one-node-core/package.json
- packages/neo-one-node-core/src/transaction/TransactionBase.ts
- packages/neo-one-node-neo-settings/package.json
- packages/neo-one-node-protocol/package.json
- packages/neo-one-node-storage-common/package.json
- packages/neo-one-node-vm/package.json
- packages/neo-one-node-vm/src/constants.ts
- packages/neo-one-react-common/src/Popover.tsx
- packages/neo-one-server-grpc/src/index.ts
- packages/neo-one-server-plugin-wallet/src/bootstrap.ts
- packages/neo-one-server-plugin/src/version.ts
- packages/neo-one-smart-contract-compiler/package.json
- packages/neo-one-ts-utils/src/print.ts
- packages/neo-one-types/bn.js/index.d.ts
- packages/neo-one-types/index.d.ts
- tsconfig/tsconfig.build.json
- yarn.lock
- temporarily use custom `bn.js` type definition which uses `export default`
- `export` a few local interfaces/functions that need to be exposed for declaration gen.
- `** @internal *` mark `TransactionBase` to hide the mixin function from declaration.
While we use the temporary `bn.js/index.d.ts` I have opened in issue in definitelyTyped:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/32178
```
yarn install
yarn build
```
`/dist` should now *only* have `.d.ts` and `.js` files.
I think the only alternative is to handwrite the declaration files.
Should fix compiling a project which uses our packages but utilizes a different `tsconfig`.
Need eyes on the `gulpfile.js` changes, not *wholly* confident in what I've done but essentially I just removed copying the typescript files to …
> fix(build): adjust several packages to allow emitting .d.ts files.

- packages/neo-one-node-data-backup/src/provider/GCloudProvider.ts
- packages/neo-one-node-data-backup/src/provider/MegaProvider.ts
- packages/neo-one-node-data-backup/src/provider/extract.ts
- packages/neo-one-server-plugin-network/src/commonBackupNode.ts
`writeBytesPerSecond` isn't required anymore, and if I'm going to be entering configs via arg inputs, I don't want this extra one hanging around.
It should have been gone already.
> chore(node): remove 'writeBytesPerSecond' backup field.

- scripts/DockerfileNode
cleanup some things in the node Dockerfile. Also copy less to the final stage, making the final image smaller.
Also, I mark the second stage of the multi-stage build. Apparently some processes can use that 🤷‍♂️ 
using:
```
COPY --from=builder tmp/neo-one/dist/neo-one/ neo-one/
```
instead of just copying all of `dist` should save some space which is fun :)
> chore(node): nit dockerfile adjustments.

- packages/neo-one-node-bin/src/utils/getConfiguration.ts
Lets the node default the PORT environment variable to its `rpc.http.port` value. Necessary for Heroku deploys.
Heroku deploys
> feat(node): add $PORT as a default for the rpc server

- packages/neo-one-server-plugin-wallet/src/contracts/SimpleToken.ts
- packages/neo-one-smart-contract-lib/src/NEP5Token.ts
- packages/neo-one-smart-contract-lib/src/__data__/contracts/SimpleToken.ts
- packages/neo-one-smart-contract-lib/src/__data__/contracts/TestICO.ts
- packages/neo-one-smart-contract-lib/src/__data__/contracts/TestToken.ts
- packages/neo-one-smart-contract-lib/src/index.ts
To allow users to readily identify they are creating a NEP5-Token, the name of the base class will be renamed from Token to NEP5Token.
> fix(token): rename Token to NEP5Token

- packages/neo-one-website/courses/0-tokenomics/2-launch/3-reactive/chapter.md
Typo in courses: "contstant" should be "constant"
None.
None.
Clarity.
None.
None.
> Fix typo in courses

- .circleci/config.yml
CI IS BROKE (and *NOT* in the normal way). I think since we deduped the yarn lock we need to refresh the cache. https://circleci.com/docs/2.0/caching/#clearing-cache
note in scenarios where you want to clear the cache:
```
Dependencies are removed from your project
```
> fix(CI): up the cache version to regenerate

- packages/neo-one-client-core/src/__tests__/sc/BaseFunctionSmartContracts.test.ts
Simple fix, jest was giving us warnings about `describe` returning a promise which is a no no. Looks like it was just a typo anyway as the `async` flags served no purpose (is there a tslint rule we can use to make sure this doesn't come up? I don't think the normal function one affects in-line functions like this example).
> fix(jest): remove unnecessary 'async' flags from test

- packages/neo-one-client-common/src/crypto.ts
- scripts/e2e/One.js
`crypto.createKeyPair` used to fail occasionally. `ec().genKeyPair()` can sometimes return a bad value, so we just need to `validate()` it before we attempt to use it. This fixes the issue.
Also, I saw an e2e test fail sometime recently I think with the EADDRINUSE again, so going to pump the range on `getAvailableMinPortForRange` and see if that nips it in the bud for good.
I tested it by isolating the currently failing test and running it x *N* to watch it fail. Then I found a solution in the `validate` function.
??
FLAKY TESTS ARE SCARED OF ME
PRs might go through faster now, not sure if we can keep up with them in terms of reviews. ;)
> fix(jest): fix a flaky crypto test - createKeyPair

- packages/neo-one-website/src/components/blog/Blog.tsx
- packages/neo-one-website/src/components/content/Content.tsx
- packages/neo-one-website/src/components/content/EditPageLink.tsx
- packages/neo-one-website/src/components/content/MainContent.tsx
- packages/neo-one-website/src/components/docs/Docs.tsx
- packages/neo-one-website/src/components/reference/Reference.tsx
- packages/neo-one-website/src/components/tutorial/Tutorial.tsx
- packages/neo-one-website/src/utils/getBlogs.ts
- packages/neo-one-website/src/utils/getDocs.ts
- packages/neo-one-website/src/utils/getTutorial.ts
Adds an "Edit this page" link to every docs, tutorial, and blog page that links to that pages respective markdown file on GitHub per issue #690. To accomplish this the commit creates a new EditPageLink component to be added to the docs, tutorial, and blog pages. Modifies getBlogs, getDocs, getTutorial utils to pass down respective page file paths down to the Docs, Tutorial, Blog components, to the Content component, finally to the MainContent component, which passes link path to EditPageLink component to render the link below MainContents markdown. The EditPageLink component contains the root GitHub URL, then adds the trailing file path that is passed down from getBlogs, getDocs, getTutorial.
I did not see any tests for the website. I'm happy to add tests if wanted. Otherwise I used …
> Add "Edit This Page" link to docs, tutorial, blog pages

- gulpfile.js
- scripts/DockerfileNode
Moved some more things around and add a filter to stop `.js` files from getting generated in `DeveloperTools` since we just want the single `index.js` generated in a bundle. Also had to add some files to the Dockerfile since `DeveloperTools` is exported from client now. 
Docker container should build again now without affecting our build.
> fix(build): fix developerTools building and the node image build

- gulpfile.js
- packages/neo-one-smart-contract-lib/src/__data__/contracts/TestDesignatedCaller.ts
- packages/neo-one-smart-contract-lib/src/__tests__/TestDesignatedCallerContract.test.ts
- packages/neo-one-smart-contract-lib/src/__tests__/__snapshots__/TestDesignatedCallerContract.test.ts.snap
- packages/neo-one-smart-contract-lib/src/index.ts
- packages/neo-one-smart-contract-lib/src/ownership/DesignatedCaller.ts
- tsconfig.json
Introduce a SmartContract Mix-in that provides basic "designated caller" functionality with a suite of tests.  This contract can only be called by a DesignatedCaller address. 
Run the included test suite:
yarn jest packages/neo-one-smart-contract-lib/src/__tests__/TestDesignatedCallerContract.test.ts
> feat(contract-mixins): add DesignatedCaller

- packages/neo-one-server-plugin-project/src/initCommand.ts
write ` .onerc ` with default config values.
Produce a .onerc config file with when ` yarn neo-one init ` is called
adds a new ` .onerc ` config file during the init process containing the default configuration as specified in ` packages/neo-one-server-plugin-project/src/types.ts `
yarn neo-one init
see that the ` .onerc ` file contains the appropriate defaults as defined by ` packages/neo-one-server-plugin-project/src/types.ts `
fixes: #1175
> feat(config): add default .onerc config

- packages/neo-one-smart-contract-lib/src/__data__/contracts/TestTransferableContract.ts
- packages/neo-one-smart-contract-lib/src/__tests__/TestTransferableOwnership.test.ts
- packages/neo-one-smart-contract-lib/src/__tests__/__snapshots__/TestTransferableOwnership.test.ts.snap
- packages/neo-one-smart-contract-lib/src/index.ts
- packages/neo-one-smart-contract-lib/src/ownership/TransferableOwnership.ts
Branched off https://github.com/neo-one-suite/neo-one/pull/1054 NEP5 Token Rename 
Introduce a SmartContract Mix-in that provides basic "transferable contract" functionality with a suite of tests.  
Run the included test suite:
yarn jest packages/neo-one-smart-contract-lib/src/__tests__/TestTransferableOwnership.test.ts
> feat(contract-mixins): add TransferableContract

- packages/neo-one-client-common/src/models/vm.ts
- packages/neo-one-node-vm/src/__tests__/opcodes.test.ts
- packages/neo-one-node-vm/src/opcodes.ts
- packages/neo-one-server-plugin-project/src/__e2e__/__snapshots__/buildCommand.test.ts.snap
- packages/neo-one-server-plugin-project/src/__e2e__/__snapshots__/buildCommandJs.test.ts.snap
- packages/neo-one-smart-contract-compiler/src/__tests__/compile/helper/contract/__snapshots__/InvokeSmartContractHelper6.test.ts.snap
- packages/neo-one-smart-contract-compiler/src/compile/helper/storage/CreateStructuredStorageHelper.ts
- packages/neo-one-smart-contract-compiler/src/compile/helper/types/WrapHelper.ts
- packages/neo-one-smart-contract-lib/src/__tests__/__snapshots__/RedToken.test.ts.snap
- packages/neo-one-smart-contract-lib/src/__tests__/__snapshots__/TestDesignatedCallerContract.test.ts.snap
- packages/neo-one-smart-contract-lib/src/__tests__/__snapshots__/TestICO.test.ts.snap
- packages/neo-one-smart-contract-lib/src/__tests__/__snapshots__/TestToken.test.ts.snap
- packages/neo-one-smart-contract-lib/src/__tests__/__snapshots__/TestTransferableOwnership.test.ts.snap
Removes the PACKSTRUCT Opcode and modifies NEWSTRUCT/NEWARRAY to be able to convert an existing array into a struct and struct into array.  This allows the use of a PACK+NEWSTRUCT pair of opcodes in place of PACKSTRUCT.
Added tests for the conversions in NEWSTRUCT and NEWARRAY.  Updated existing tests to reflect the slightly higher GAS costs of neo-one compiled contracts.
Previously the plan was to implement our PACKSTRUCT in the neo-vm as per https://github.com/neo-project/neo-vm/issues/51 and https://github.com/neo-project/neo-vm/pull/88.  This new solution was suggested and implemented here: https://github.com/neo-project/neo-vm/pull/91.
Very slightly higher GAS cost for neo-one compiled smart contracts.  
https://github.com/neo-one-suite/neo-one/issues/1254
> refactor(PACK+NEWSTRUCT): Replace PACKSTRUCT with PACK+NEWSTRUCT

- packages/neo-one-server-plugin-network/src/__e2e__/createNetworkMain.test.ts
Reduces the expected peers in `createNetworkMain` test to 3 since this flakes all the time in CI. Only a suggestion do with this what you will.
Hopefully CI doesn't fail this again, and if it does hopefully it actually indicates something.
:thinking: a retry approach?
less e2e flakiness
> fix(e2e): reduce expected peer connections to 3

- renovate.json
title, putting it on a schedule allows us to "kick out" failing dependency updates without them immediately coming back. 
Also I think we can comfortably separate the misc major/minor updates.
(by default it will update its branches on 2am every day)
> feat(renovate): seperate misc major/minor and add update schedule

- tslint.json
title, clean up the annoying green underlines.
see: https://palantir.github.io/tslint/rules/file-name-casing/ & https://palantir.github.io/tslint/rules/strict-boolean-expressions/
> chore(tslint): cleanup some things it complained about

- packages/neo-one-server-plugin-project/src/initCommand.ts
fix #1383
Use relative paths in the `.onerc`
utilize `path.relative()`,
explicitly `spread` the part of the config that's used: `codegen` after scrubbing `paths`
yarn neo-one init
// review .onerc
#1383
> fix(onerc): use relative paths

- packages/neo-one-server-client/src/ServerManager.ts
enhanced server version check to report newer version if version difference is ` > 0 `
Updated variable names to be a bit more reasonable, added missing ` > 0 ` check
set NPMVersion to 3.0 & received proper "new version available" 
otherwise the version in npm `1.1.0` is < `1.2.0`  
fixes #1380
> fix(server-ver-check): fix server version check

- packages/neo-one-client-core/src/provider/JSONRPCHTTPProvider.ts
- packages/neo-one-server-plugin-network/src/node/NEOONENodeAdapter.ts
- packages/neo-one-server-plugin-wallet/src/__data__/bootstrapTestUtils.ts
- packages/neo-one-server-plugin-wallet/src/__e2e__/bootstrap20Wallets.test.ts
- packages/neo-one-server-plugin-wallet/src/__e2e__/bootstrapRPC.test.ts
Re-enable the RPC RateLimiter middleware with appropriate defaults that allow it to pass tests but also still be a failsafe if someone messed up and had a client send a TON of requests at once.
> feat(rpc): Re-enable rateLimit middleware on the rpc server

- .vscode/settings.json
title,
also remove some other deprecated settings we had laying around.
> fix(tslint): re-enable auto fixing lint errors on save

- gulpfile.js
Title, the bin files don't need `.ts` or `.d.ts` files generated for them since we are just running them with node.
additionally, stop exporting `__data__` and `__test__` folders with `@neo-one/smart-contract-lib` (started exporting them because of adding the `ownership` folder using a `**/*` glob).
Fixes #1425
> chore(build): remove declaration generation from bin creation

- packages/neo-one-client-common/src/crypto.ts
Changed the call to `createHash` to use the name `ripemd160` instead of `rmd160` when running under Electron. `rmd160` as a hash algorithm name is no longer supported since Electron 4, when the Electron team switched to the BoringSSL library which uses the `ripemd160` name instead of OpenSSL's `rmd160` name.
Manually tested under Electron v5.0.2 - the Neo-One node would not run under Electron without this change. 
No other designs considered
Neo-One projects requiring RIPEMD160 hashing will be compatible with Electron
No drawbacks that I can see
No …
> pass hash name as ripemd160 instead of rmd160 in Electron

- packages/neo-one-server-plugin-network/src/__e2e__/createNetworkTest.test.ts
- packages/neo-one-server-plugin-project/src/__data__/ico/one/generated/Escrow/contract.ts
- packages/neo-one-server-plugin-project/src/__data__/ico/one/generated/ICO/contract.ts
- packages/neo-one-server-plugin-project/src/__data__/ico/one/generated/Token/contract.ts
- packages/neo-one-server-plugin-project/src/__data__/ico/one/generated/client.ts
- packages/neo-one-server-plugin-project/src/__data__/ico/one/generated/sourceMaps.ts
- packages/neo-one-server-plugin-project/src/__data__/icojs/one/generated/Escrow/contract.js
- packages/neo-one-server-plugin-project/src/__data__/icojs/one/generated/ICO/contract.js
- packages/neo-one-server-plugin-project/src/__data__/icojs/one/generated/Token/contract.js
- packages/neo-one-server-plugin-project/src/__data__/icojs/one/generated/client.js
- packages/neo-one-server-plugin-project/src/__data__/icojs/one/generated/sourceMaps.js
- packages/neo-one-server-plugin-project/src/__e2e__/__snapshots__/buildCommand.test.ts.snap
- packages/neo-one-server-plugin-project/src/__e2e__/__snapshots__/buildCommandJs.test.ts.snap
Update E2E snapshot tests, bring `createNetworkTest` expected peers in line with `createNetworkMain` (we lowered the latter for CI, makes sense to also lower this one, + it just failed on me in a test).
> chore(build): update e2e snapshots, bring test inline

- packages/neo-one-website/src/components/content/MainContent.tsx
- packages/neo-one-website/src/elements/Markdown.tsx
Update our scroll-sync method to match what React-Router recommends now. https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/docs/guides/scroll-restoration.md
start the website with:
```
yarn website:start:dev-builds
```
and in a seperate terminal
```
yarn website:start:dev
```
Click a really long article, like in `/Docs`, and then click other links. You'll see you are brought to the top of the page again now.
It was really annoying before.
#1340
> fix(website): fix the scroll sync issue

- packages/neo-one-website/docs/4-node/1-docker.md
- packages/neo-one-website/docs/4-node/2-kubernetes.md
- packages/neo-one-website/docs/4-node/3-docker-compose.md
- packages/neo-one-website/docs/4-node/4-build-from-source.md
- packages/neo-one-website/docs/4-node/5-heroku.md
- packages/neo-one-website/docs/4-node/6-configuration.md
Update the node documentation for the website in preparation for #1478  
I made edit the configuration reference format more. Since things get a little more nested after the `environment` options I switch how I list the options. Not sure if it should be like that tho :thinking:
People don't rip hair out with wrong configs using new node.
fix #1483
> chore(docs): update node documentation for new config

- packages/neo-one-server-plugin-project/src/initCommand.ts
- packages/neo-one-server-plugin-project/src/utils/loadProjectConfig.ts
Check the package.json of the current working directory for key dependencies in order to deduce the project framework.
Additional do some `Set` wrapping for the tsconfig.exclude overrides we do. Previously if someone did `yarn neo-one init` multiple times it would keep adding the same file to the end of the exclude. Fixed now :)
kind of complicated but if you do the various `create-x-app`s you can see that the dependencies I check for are the ones generated by the frameworks. You can quickly test it works for react using
```
yarn build
node ./dist/neo-one/packages/neo-one-cli/bin/neo-one init
```
and see that the `.onerc` has "react" as its framework.
It looks like only angular sets up additional `.json` files that could be used to identify it as angular, but it also looks like that name …
> feat(cli): 'yarn neo-one init' finds framework, warns otherwise

- packages/neo-one-server-plugin-project/src/build/index.ts
- packages/neo-one-server-plugin-project/src/buildCommand.ts
Catch but don't throw errors when building smart contracts with `--watch` so that it doesn't fail and have to be restarted on TS error or equivalent.
1. create `./one/contracts/Token.ts` with
```
import { SmartContract } from '@neo-one/smart-contract';
export class Token extends SmartContract {}
```
2. run `yarn watch` in another terminal
3. run
```
node ./dist/neo-one/packages/neo-one-cli/bin/neo-one build --watch
```
4. comment out the `import { SmartContract } from '@neo-one/smart-contract';` line.
5. ??? it doesn't crash out now
here is the old output when you did the above:
```
✔ Load project configuration
✖ Find contracts
→ Error: {"paths":{"contracts":"/Users/danielbyrne/neo-one/one/contracts","genera…
Deploy dev contracts
Synchronize project
✖ Error: …
```
> fix(compiler): catch errors properly when using neo-one build --watch

- gulpfile.js
Big surprise the build was still broken. This adds regex transformations to the `gulpfile` that SHOULD be the final fix that is needed. I did an full audit of the `dist` today so this was the only red-flag I saw.
```
yarn build
```
the imports aren't jank relative paths with a bunch of `../../../`s
fix #1509
> fix(build): fix import transformations

- packages/neo-one-website/docs/0-installation/1-environment-setup.md
- packages/neo-one-website/tutorial/tutorial.md
Documented polyfill requirements and fixed a mistake in the tutorial - accountIDs[0] has no NEO and will fail to mintTokens. 
#783, #1341
> docs(polyfill): document polyfill requirements + fix incorrect line

- packages/neo-one-client-core/src/errors.ts
- packages/neo-one-client-core/src/user/LocalUserAccountProvider.ts
- packages/neo-one-client-core/src/user/UserAccountProviderBase.ts
- packages/neo-one-client-full-core/src/user/LocalUserAccountProvider.ts
Separate LocalUserAccountProvider into abstract base class and higher order classes.
LocalUserAccountProvider refactored into a base class and higher order classes.  The base class should take care of all setup and common functionality.  The higher order class takes care of actually executing transactions & invocations.  
LocalUserAccountProvider tests still pass
Simplifies work for DAPI and any other providers we add in the future
> refactor(LocalUserAccountProvider): Separate LocalUserAccountProvider

- renovate.json
Not sure why we removed the groupings to start with, but the PRs are adding up so I'm putting it back.
> chore(rennovate): add groups back to rennovate

- renovate.json
Changes `renovate` bot config to run in the wee hours of the morning, according to our time zone. This way it won't be making changes while we could be pushing our own changes.
Fixes: #1536 
After this is merged it should always run between midnight and 5AM.
None.
Less risk for breaking `bors`
Slack notifications while we try to sleep.
#1536
> chore(renovate): change renovate bot schedule to be more ideal

- packages/neo-one-node-core/src/BlockBase.ts
- packages/neo-one-node-core/src/Header.ts
- packages/neo-one-node-core/src/invocationResult/InvocationResultError.ts
- packages/neo-one-node-core/src/invocationResult/InvocationResultSuccess.ts
- packages/neo-one-node-core/src/payload/ConsensusPayload.ts
- packages/neo-one-node-core/src/payload/message/ChangeViewConsensusMessage.ts
- packages/neo-one-node-core/src/payload/message/PrepareRequestConsensusMessage.ts
- packages/neo-one-node-core/src/storageChange/StorageChangeAdd.ts
- packages/neo-one-node-core/src/storageChange/StorageChangeDelete.ts
- packages/neo-one-node-core/src/storageChange/StorageChangeModify.ts
- packages/neo-one-node-core/src/transaction/ClaimTransaction.ts
- packages/neo-one-node-core/src/transaction/ContractTransaction.ts
- packages/neo-one-node-core/src/transaction/EnrollmentTransaction.ts
- packages/neo-one-node-core/src/transaction/InvocationTransaction.ts
- packages/neo-one-node-core/src/transaction/IssueTransaction.ts
- packages/neo-one-node-core/src/transaction/MinerTransaction.ts
- packages/neo-one-node-core/src/transaction/PublishTransaction.ts
- packages/neo-one-node-core/src/transaction/RegisterTransaction.ts
- packages/neo-one-node-core/src/transaction/StateTransaction.ts
- packages/neo-one-node-core/src/transaction/attribute/BufferAttribute.ts
- packages/neo-one-node-core/src/transaction/attribute/ECPointAttribute.ts
- packages/neo-one-node-core/src/transaction/attribute/UInt160Attribute.ts
- packages/neo-one-node-core/src/transaction/attribute/UInt256Attribute.ts
- packages/neo-one-node-core/src/transaction/state/StateDescriptor.ts
- packages/neo-one-node-protocol/src/Message.ts
- packages/neo-one-node-protocol/src/payload/FilterLoadPayload.ts
- packages/neo-one-node-protocol/src/payload/NetworkAddress.ts
About half of the time that an `InvalidFormatError` was thrown it didn't have a message along with it, making debugging harder. This adds descriptive messages to those remaining times that `InvalidFormatError` is thrown.
Fixes: #675 
None.
I think I described the errors well but someone with knowledge of the architecture may want to glance at them to be sure the messages are accurate.
More descriptive errors when `InvalidFormatError`s are thrown.
None.
Fixes: #675
> fix(core, protocol): describe InvalidFormat errors

- packages/neo-one-website/package.json
- packages/neo-one-website/src/components/reference/common/utils.tsx
- yarn.lock
Removes the `html-to-react` package, which was used in the website. It was used to convert Prism.js-highlighted HTML to React code. `Prism.highlight()` returned a string which was then passed to `html-to-react`. I simply removed the `html-to-react` package and instead of passing the string of highlighted HTML code to `html-to-react` I passed it to `dangerouslySetInnerHtml` in its parent `<span>` element.
Fixes #748 
Run `yarn website:start:dev-builds` and `yarn website:start:dev` and go to the *Resources* page and click on any of the references to see the syntax highlighting in the code examples, complete with links to other source code definitions
It's possible I'm not understanding what we want from this issue. I looked into how to use hooks with Prism.js in order to override how it …
> fix(website): remove html-to-react package

- renovate.json
Renovate doesn't seem to be running when we want it to. This is a second attempt to fix that and make it run in the middle of the night.
After the merge watch that Renovate only opens PRs after 12am midnight and before 5am
None
No Renovate commits during the day
None
#1536
> fix(renovate): fix broken renovate schedule/timezone

- packages/neo-one-node-bin/src/utils/extractConfigurations.ts
- packages/neo-one-node-http-rpc/src/rpcServer$.ts
- packages/neo-one-node/src/FullNode.ts
- packages/neo-one-website/docs/4-node/1-docker.md
- packages/neo-one-website/docs/4-node/6-configuration.md
Remove the `https` option from the node. We never used it and don't plan to support it.
Fixes #1609
> chore(node): remove 'https' option from RPC Server

- renovate.json
Renovate seems confused and submits PRs in the middle of the day still, clogging our CI jobs. It's possible that it is misinterpreting 12am as 12pm, so I changed it to be after 1am. I also added on weekends so it runs anytime during the weekends. The submitted change is almost directly from the renovate docs, so this *should* work: https://renovatebot.com/docs/configuration-options/#schedule
Watch for when renovate makes PRs and updates.
None.
Better schedule.
None.
#1536
> fix(renovate): tell renovate to run on weekends as well

- packages/neo-one-client-switch/src/browser/tracing.ts
- packages/neo-one-client-switch/src/node/tracing.ts
- packages/neo-one-logger/src/loggers.ts
- packages/neo-one-node/src/startFullNode.ts
- scripts/website/webpack/preview.ts
- scripts/website/webpack/testRunner.ts
Fixes the website build. 
For now we add some more cache-loading to `@neo-one/client-switch/browser/tracing.ts` because importing `@opencensus/web-core` causes a tracer to start even though we don't want it to (yet). 
I think once we hook up the inital trace/spans described here https://github.com/census-instrumentation/opencensus-web this won't be necessary anymore.
Also adds a browser switch to `createLogger` options since we don't want to enable a `pino.destination` in the browser (it fails load the definition entirely when in browser)
> fix(web): fix logging / opencensus imports for website

- packages/neo-one-client-core/src/Client.ts
- packages/neo-one-client-core/src/__data__/data.ts
- packages/neo-one-client-core/src/__tests__/__snapshots__/args.test.ts.snap
- packages/neo-one-client-core/src/__tests__/args.test.ts
- packages/neo-one-client-core/src/args.ts
Add arg assertions to the client smart contract APIs in `neo-one-client-core/src/Client.ts`. I added two arg assertion methods in `neo-one-client-core/src/args.ts` and added tests for those new methods in `neo-one-client-core/src/__tests__/args.test.ts`. The two new methods in `args.ts` are:
- `assertNullableIterOptions` for asserting `IterOptions` parameters
- `assertNullableNumber` for asserting a number which could also be undefined
- `assertInvokeSendUnsafeReceiveTransactionOptions` for asserting `InvokeSendUnsafeReceiveTransactionOptions` type
- `assertNullableSendTo` for ^
- `assertNullableSendFrom` for ^^
Fixes: #722 
To run tests for all of `neo-one-client-core`:
`yarn jest packages/neo-one-client-core/src/**/*`
Run tests just for the changed files:
`yarn jest …
> fix(core): fix arg assertions in client smart contract APIs

- .github/workflows/dockerhub.yaml
- actions/dockerhub/entrypoint.sh
- packages/neo-one-cli/package.json
- packages/neo-one-client-switch/package.json
- packages/neo-one-node-bin/package.json
Files that build a bin need to have `import-local` in their package.json.
Also add `regenerator-runtime` as a dep in `@neo-one/client-switch`, I think it was implicit before.
All of these were an issue when I made a tmp-project and ran:
```
yarn add @neo-one/suite
yarn neo-one init
```
and installing them myself fixed the issue.
also adding some echos for the docker file entrypoint so we can debug the tag actions, will revert.
> feat(build): fix bin package.jsons

- packages/neo-one-suite/package.json
###
Until we remove @neo-one/smart-contract-lib in the future the suite package needs it in its packages so all of the neo-one commands can be run.
> fix(suite): add smart-contract-lib to @neo-one/suite

- gulpfile.js
Building the `neo-one-react-common` package caused problems with importing static assets into components for that package. The path for static imports was wrong. This fixes that problem.
I ran `yarn build` and saw that the imports were correct in the `dist/neo-one/packages/neo-one-react-common`. These are the affected built files/components:
`Background.js`
`FileIcon.js`
`LineLogoPrimary.js`
`Logo.js`
`Monogram.js`
None
Correct static imports
None
#1719
> fix(gulp): fix static imports in neo-one-react-common

- packages/neo-one-developer-tools-frame/src/ResizeHandler.ts
- packages/neo-one-developer-tools-frame/src/Toolbar.tsx
- packages/neo-one-smart-contract-codegen/src/__tests__/client/__snapshots__/genBrowserClient.test.ts.snap
- packages/neo-one-smart-contract-codegen/src/client/genBrowserClient.ts
Fix the developer tools clipping. Also add an `ifProp` switch to stop some initial transition clipping, also changes the behavior of the size observer. Works much better now after test and looking at the i-frame in different instances.
Fixes #1726
> fix(web): fix developer tools clipping

- scripts/website/runCypress.ts
Bumps the time from 3 minutes to 5 minutes for the website to startup in the `runCypress` script. 3 minutes wasn't enough time to finish the `website:start:prod` script, thus causing the Cypress tests to fail when run in `--local` mode.
Run `yarn test:cypress-express --local` locally and see the Cypress express test pass.
None.
Passing tests.
None.
#1740
> fix(cypress): more time for website:start:prod to finish in cypress script

- package.json
- packages/neo-one-cli/package.json
- packages/neo-one-editor/package.json
- packages/neo-one-local-browser/package.json
- packages/neo-one-smart-contract-compiler-node/package.json
- packages/neo-one-smart-contract-compiler/package.json
- packages/neo-one-smart-contract-typescript-plugin/package.json
- packages/neo-one-smart-contract-typescript-plugin/src/SmartContractPlugin.ts
- packages/neo-one-ts-utils/package.json
- packages/neo-one-typescript-concatenator/package.json
- yarn.lock
Reverts back to TS version 3.5.3. There's fatal issue with TS v3.6.2 which breaks our website editor. The fix for this error will be released in v3.6.3, hopefully to be released any day now.
Fixes: #1743
Reinstall `node_modules` and run `yarn website:start-testRunner`, navigate to `localhost:8081` and open the console. You shouldn't see any errors.
None.
Editor working until v3.6.3 patch.
I'm not sure if there's anything we needed in TS v3.6.2.
#1743
> fix(ts): revert back to TS v3.5.3 until v3.6.3 is released

- actions/dockerhub/entrypoint.sh
`dockerhub pull neoonesuite/node` defaults to pulling the image tagged as `latest`.  So, we should be publishing a `latest` tag in addition to the SHA tagged images.
> fix(dockerhub latest): always publish/overwrite the "latest" tag in addition to the SHA tag

- .github/workflows/dockerhub.yaml
- actions/dockerhub/entrypoint.sh
Github action to publish node-bin images to dockerhub was not working for tags/releases.  This should fix the problem by triggering a publish when a a release is created.
Tested here: https://github.com/neo-one-suite/test-actions
Published images here: https://hub.docker.com/r/afragapane/test-repo/tags
#1777
> fix(dockerhub release): publish to dockerhub when a release is created

- bors.toml
`bors` was timing out after the Cypress-CI PR went it. It turns out that `bors` was looking for `Cypress / cypress12 (pull_request)` but should have been looking for `Cypress / cypress12 (push)` since `bors` is pushing to the staging branch and not opening a pull request on the staging branch. Thus it was looking for the wrong CI check to pass before merge it with `master` branch. This fixes that problem.
See that this fixes `bors`.
None.
Fixes `bors`.
None.
#1446
> fix(bors): bors problem fixed forever

- bors.toml
Sanity check for `bors`. Take out Cypress requirement to see if `bors` will merge. If `bors` works without requiring Cypress then we'll be reassured that we have pinpointed the source of the problem.
None.
None.
Testing.
None.
#1446
> fix(bors): try removing cypress from bors requirement

- packages/neo-one-editor/src/loaders/packagesLoader.ts
Website courses were not working - I think this is because @neo-one/node-browser was not being included and so couldn't be found.  This attempts to fix the problem.
> fix(website course): include neo-one-node-browser in website

- bors.toml
Removes `cypress` test from the `bors` required checks while we figure out how to make this work. The Cypress test will still run in CI but `bors` won't check for it when merging.
See that `bors` works.
None.
`bors` merging.
This means that bugs *could* slip through when `bors` merges multiple PRs together. But this should be caught in the very next rebase/PR. And we want to have this working in `bors` very soon.
#1446
> fix(bors): remove bors check for Cypress

- packages/neo-one-cli/src/__e2e__/cmd/new/privateKey.test.ts
Added test to confirm `neo-one new private-key` logs a correctly formed privateKey to the console.
#1683
> test(new private-key): add e2e test for new private-key command

- packages/neo-one-editor/src/engine/main/initializeFileSystem.ts
- packages/neo-one-editor/src/loaders/packagesLoader.ts
- packages/neo-one-editor/src/loaders/packagesLoaderEntry.js
- packages/neo-one-local-browser/src/filesystem/PouchDBFileSystem.ts
- packages/neo-one-react-common/src/LoadingDots.tsx
title, changes `packagesLoader.ts` to use per-file dependencies rather than directory context dependencies. Also stops using `@neo-one/utils` for a simple filter function as that was causing babel issues.
> fix(website): fixup neo-one source file loading into pouchDB

- common/config/rush/command-line.json
- packages/neo-one-build-tools/src/clean.ts
Adds a `rush` command to easily delete all the `*.build.log` files. The `-d` or `--debug` flag will log exactly what it's deleting. The `-f` or `--full` flag will also delete all the `lib` directories, and `package-deps.json` files.
Run `rush clean -d` to see it delete all the `*.build.log` files. The `-d` or `--debug` flag will log exactly what it's deleting.
Run `rush clean -d -f` to see it delete all the `lib` directories and `package-deps.json` files as well.
None.
Ability to clean out files with a single command.
None.
#1820
> feat(rush clean): add new rush clean command/script

- packages/neo-one-cli/src/__data__/projects/ico-Js/codegen/client.js
- packages/neo-one-cli/src/__data__/projects/ico-angular/codegen/client.ts
- packages/neo-one-cli/src/__data__/projects/ico-angularJs/codegen/client.js
- packages/neo-one-cli/src/__data__/projects/ico-vue/codegen/client.ts
- packages/neo-one-cli/src/__data__/projects/ico-vueJs/codegen/client.js
- packages/neo-one-cli/src/__data__/projects/ico/codegen/client.ts
- packages/neo-one-client/src/index.ts
- packages/neo-one-smart-contract-codegen/src/__tests__/__snapshots__/genCommonFiles.test.ts.snap
- packages/neo-one-smart-contract-codegen/src/__tests__/client/__snapshots__/genClient.test.ts.snap
- packages/neo-one-smart-contract-codegen/src/client/genClient.ts
Setup DapiUserAccountProvider by default during codegen.  If the codegen detects `globalThis.neoDapi` to be set, then it will setup a dapi based on this.  
Tested on a project with O3's dapi.  
1. Download O3 desktop and create a wallet
2. Use this generated code in a neo-one app
3. import neoDapi from 'neo-dapi' and `globalThis.neoDapi = neoDapi` at the entry point
4. Observe the dapi connects as expected
#1687
> Dapcodegen

- packages/neo-one-node-vm/src/__tests__/opcodes.test.ts
- packages/neo-one-node-vm/src/__tests__/stackItem/StackItem.test.ts
- packages/neo-one-node-vm/src/__tests__/stackItem/StackItemBase.test.ts
- packages/neo-one-node-vm/src/__tests__/stackItem/__snapshots__/StackItem.test.ts.snap
- packages/neo-one-node-vm/src/opcodes.ts
- packages/neo-one-node-vm/src/stackItem/NullStackItem.ts
- packages/neo-one-node-vm/src/stackItem/StackItem.ts
- packages/neo-one-node-vm/src/stackItem/StackItemBase.ts
- packages/neo-one-node-vm/src/stackItem/StackItemType.ts
- packages/neo-one-node-vm/src/stackItem/deserializeStackItem.ts
- packages/neo-one-node-vm/src/stackItem/index.ts
- Adds the new `Null` stack item to the VM, including unit tests.
- Adds the `PUSHNULL` and `ISNULL` OpCodes to the VM, including unit tests.
- Adds `isNull()` method to `StackItemBase`, including unit tests.
- Also changes the hex code for `DUPFROMALTSTACKBOTTOM` OpCode to match the hex code in the NEO C# VM.
Run `yarn jest`...
- `packages/neo-one-node-vm/src/__tests__/opcodes.test.ts`
- `packages/neo-one-node-vm/src/__tests__/StackItem.test.ts`
- `packages/neo-one-node-vm/src/__tests__/StackItemBase.test.ts`
I was having trouble running the unit tests due to a TypeScript error. So there's likely a small edit on the way to the `NullStackItem` class to fix this.
None.
Gets us one step closer to NEO v3.0
The NEO v3 VM/compiler could be changed from now until NEO v3 launch, which would mean …
> feat(vm): add null stack item, PUSHNULL, ISNULL, and tests

- packages/neo-one-client-common/src/models/vm.ts
- packages/neo-one-node-vm/src/__tests__/__snapshots__/syscalls.test.ts.snap
- packages/neo-one-node-vm/src/__tests__/syscalls.test.ts
- packages/neo-one-node-vm/src/errors.ts
- packages/neo-one-node-vm/src/syscalls.ts
Adds new `SYSCALL` to the `neo-one-node-vm`: `System.Blockchain.GetTransactionFromBlock`. Also added tests for this new SysCall and a new VM error for invalid transaction index in a block's transaction list.
The implementation of this SysCall in the NEO Project C# code can be found here: https://github.com/neo-project/neo/blob/master/src/neo/SmartContract/InteropService.cs#L374
This should be thoroughly reviewed by someone else to check that I'm on the right track. It's probably best that I discuss this in-person with someone because I have a few questions about when to throw errors vs when to push a null stack item, which itself appears to be a new `StackItem` in Neo3.
Run `yarn jest packages/neo-one-node-vm/src/__tests__/syscalls.test.ts`
None.
Gets us one step closer to NEO v3.0
The …
> feat(vm): add system.blockchain.gettransactionfromblock syscall to vm

- packages/neo-one-build-tests/jest/unit-ci.js
- packages/neo-one-build-tests/jest/unit.js
- packages/neo-one-build-tests/tsconfig.jest.json
jest unit tests no longer require rebuilding locally. CI & E2E tests will still require built files.
> feat(jest): local unit tests now use .ts to not require rebuilding

- packages/neo-one-client-full-common/src/__tests__/models/ContractPermissionDescriptorModel.test.ts
- packages/neo-one-node-blockchain/src/Blockchain.ts
- packages/neo-one-node-blockchain/src/__tests__/StorageCache.test.ts
- packages/neo-one-node-vm/src/__tests__/__snapshots__/syscalls.test.ts.snap
- packages/neo-one-node-vm/src/__tests__/syscalls.test.ts
- packages/neo-one-node-vm/src/errors.ts
- packages/neo-one-node-vm/src/syscalls.ts
- Updates the new SysCall `System.Contract.Call`, which replaces the old OpCodes `APPCALL`, `TAILCALL`, `CALL_E`, `CALL_ED`.
- Adds unit tests for this new SysCall. Also makes minor fixes to some SysCalls and their respective unit tests. Some SnapShots have not been updated, but I want to keep it that way for the moment because a handful of SysCalls still need to be added/updated, and their respective tests need to be changed as well.
- Adds unit tests for the new methods in the `ContractPermissionDescriptorModel`.
- `rush test -t packages/neo-one-node-vm/src/__tests__/syscalls.test.ts`
- `rush test -t packages/neo-one-client-full-common/src/__tests__/models/ContractPermissionDescriptorModel.test.ts`
None.
One step closer to NEO 3.0.
`System.Contract.Call` is quite complicated, so we may …
> feat(vm): add syscall system.contract.call, plus more fixes

- packages/neo-one-client-common/src/models/types.ts
- packages/neo-one-node-core/src/StorageItem.ts
This does more work to add to the revert from earlier to add back keys and hashes to `StorageItem`. See [here](https://github.com/neo-one-suite/neo-one/pull/1950). There are some places that I missed changing back. Note that this also changes back to the use of `flags` instead of just the `isConstant`, which keeps this part of the `StorageItem` as more extensible in the future should NEO decide to add more flags. This seems especially pertinent given that NEO changes thing in unpredictable ways.
None.
None.
Closer to NEO 3.0
None.
None.
> fix(storageitem): revert further storageitem changes

- packages/neo-one-client-common/src/models/vm.ts
- packages/neo-one-node-vm/src/__tests__/stackItem/__snapshots__/serializeJson.test.ts.snap
- packages/neo-one-node-vm/src/__tests__/syscalls/__snapshots__/native.test.ts.snap
- packages/neo-one-node-vm/src/__tests__/syscalls/native.test.ts
- packages/neo-one-node-vm/src/native/NativeContract.ts
- packages/neo-one-node-vm/src/native/index.ts
- packages/neo-one-node-vm/src/native/tokens/GasToken.ts
- packages/neo-one-node-vm/src/native/tokens/Nep5Token.ts
- packages/neo-one-node-vm/src/syscalls.ts
Adds tests for the GAS Token and Nep5 methods of the NEO token.  These are tested as syscalls through the syscall unit tests.  
This tests the native contracts as unit tests with storage mocked out.  Eventually we will also want to add tests which include storage and blockchain state, similar to the execute tests.  
https://github.com/neo-one-suite/neo-one/issues/1953
> test(native contracts): Add unit tests for GAS & NEO native contract methods

- common/config/rush/command-line.json
Adds the ability to run `jest` unit tests in watch mode with the `--watch` flag
1. Run a unit test in watch mode, like `rush test -t packages/neo-one-client-common/src/__tests__/common.test.ts --watch`
2. Change `common.ts` or `common.test.ts` and watch Jest re-run the test
> feat(jest watch): add watch flag to run jest in watch mode

- packages/neo-one-node-core/src/vm.ts
- packages/neo-one-node-vm/src/__tests__/syscalls/__snapshots__/storage.test.ts.snap
- packages/neo-one-node-vm/src/__tests__/syscalls/blockchain.test.ts
- packages/neo-one-node-vm/src/__tests__/syscalls/json.test.ts
- packages/neo-one-node-vm/src/__tests__/syscalls/runtime.test.ts
- packages/neo-one-node-vm/src/__tests__/syscalls/storage.test.ts
- packages/neo-one-node-vm/src/constants.ts
- packages/neo-one-node-vm/src/syscalls.ts
Some minor updates to SysCall fees and returning NullStackItems where applicable.
`rush test -t packages/neo-one-node-vm/src/__tests__/syscalls/storage.test.ts`
`rush test -t packages/neo-one-node-vm/src/__tests__/syscalls/runtime.test.ts`
`rush test -t packages/neo-one-node-vm/src/__tests__/syscalls/blockchain.test.ts`
`rush test -t packages/neo-one-node-vm/src/__tests__/syscalls/json.test.ts`
Closer to NEO 3.0
#1874 
#1974
> fix(syscalls): minor updates to syscalls

- .circleci/config.yml
- common/changes/@neo-one/node-bin/fix-wallaby_2020-02-10-22-10.json
- jest.config.js
- packages/neo-one-build-tests/jest/base.js
- packages/neo-one-node-bin/src/__e2e__/cmd/consensus.test.ts
- wallaby.js
Fixes the Wallaby config to work on our giant RushJS monorepo.
Run Wallaby. It takes about 8 min to run completely.
None.
Wallaby working.
None.
#1971 
#1891
> fix(wallaby): fix wallaby config to work with rush

- scripts/DockerfileNodeGSUtil
add the WORKDIR command to mirror the `node` docker image, previously the entry point wasn't working because the copy commands were 1 level lower than expected.
> fix(docker): node-gsutil fix

- common/changes/@neo-one/smart-contract-compiler/new-ts_2020-02-27-21-52.json
- common/changes/@neo-one/typescript-concatenator/new-ts_2020-02-27-21-52.json
- packages/neo-one-smart-contract-compiler/src/__tests__/compile/declaration/ClassDeclarationCompiler.test.ts
- packages/neo-one-smart-contract-compiler/src/__tests__/compile/declaration/TypeAliasDeclarationCompiler.test.ts
- packages/neo-one-smart-contract-compiler/src/__tests__/compile/declaration/__snapshots__/ClassDeclarationCompiler.test.ts.snap
- packages/neo-one-smart-contract-compiler/src/__tests__/compile/expression/AwaitExpressionCompiler.test.ts
- packages/neo-one-smart-contract-compiler/src/__tests__/compile/expression/CallExpressionCompiler.test.ts
- packages/neo-one-smart-contract-compiler/src/__tests__/compile/expression/ElementAccessExpressionCompiler.test.ts
- packages/neo-one-smart-contract-compiler/src/__tests__/compile/expression/ObjectLiteralExpressionCompiler.test.ts
- packages/neo-one-smart-contract-compiler/src/__tests__/compile/expression/PropertyAccessExpressionCompiler.test.ts
- packages/neo-one-smart-contract-compiler/src/__tests__/compile/expression/__snapshots__/AwaitExpressionCompiler.test.ts.snap
- packages/neo-one-smart-contract-compiler/src/__tests__/compile/expression/__snapshots__/ObjectLiteralExpressionCompiler.test.ts.snap
- packages/neo-one-smart-contract-compiler/src/compile/expression/ElementAccessExpressionCompiler.ts
- packages/neo-one-smart-contract-compiler/src/compile/expression/PropertyAccessExpressionCompiler.ts
- packages/neo-one-smart-contract-compiler/src/compile/helper/function/CallLikeHelper.ts
- packages/neo-one-typescript-concatenator/src/__data__/snippets/import/entry.ts
- packages/neo-one-typescript-concatenator/src/__data__/snippets/import/onlyTypes.ts
- packages/neo-one-typescript-concatenator/src/__tests__/__snapshots__/concatenate.test.ts.snap
Upgrades Smart-Contract compiler to support new TS language features:
Features from TS v3.7:
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html
- Added in previous TS PR
- Not supported
- No change needed
- Should be supported in VS Code without change from us
Features from TS v3.8.1-rc:
https://devblogs.microsoft.com/typescript/announcing-typescript-3-8-rc/
- Added in previous TS PR
- Not supported
- All Unit Tests
- `rush test`
- `rush e2e`
- Optional Chaining
- `rush test -t packages/neo-one-smart-contract-compiler/src/__tests__/compile/expression/CallExpressionCompiler.test.ts`
- `rush test -t packages/neo-one-smart-contract-compiler/src/__tests__/compile/expression/ElementAccessExpressionCompiler.test.ts`
- `rush test -t …
> feat(ts): add TS v3.7/3.8 language features

- packages/neo-one-client-common/src/models/types.ts
- packages/neo-one-client-common/src/types.ts
- packages/neo-one-client-core/src/__data__/factory.ts
- packages/neo-one-client-core/src/__tests__/provider/NEOONEDataProvider.test.ts
- packages/neo-one-client-core/src/__tests__/provider/__snapshots__/NEOONEDataProvider.test.ts.snap
- packages/neo-one-client-core/src/errors.ts
- packages/neo-one-client-core/src/provider/NEOONEDataProvider.ts
- packages/neo-one-client-core/src/provider/convert.ts
Convert NEOONEDataProvider to work with the new JSONRPCClient updated for neo 3.0 + the official node.  This really only includes support for the basic methods.  We will need to find ways to better support Invocation Data, Actions, and Storage/Storage iteration.  Easy support for NEO & GAS will come with a more generic refactor of how the client supports nep-5 contracts. 
Added unit tests.  Also performed simple tests with the neo 3.0 testnet
3.0 + official node compatibility.
Loss of invocation data & easy access to storage iteration.  Loss of developer client methods.
> feat(NEOONEDataProvider 3.0): Convert NEOONEDataProvider to work with 3.0 + official node

- common/changes/@neo-one/client-core/node-restore_2020-03-16-20-14.json
- common/changes/@neo-one/client-switch/node-restore_2020-03-16-20-14.json
- common/changes/@neo-one/node-rpc-handler/node-restore_2020-03-16-20-14.json
- common/changes/@neo-one/node/node-restore_2020-03-16-20-14.json
- common/config/rush/browser-approved-packages.json
- common/config/rush/yarn.lock
- packages/neo-one-client-core/src/user/UserAccountProviderBase.ts
- packages/neo-one-client-switch/src/browser/tracing.ts
- packages/neo-one-client-switch/src/node/tracing.ts
- packages/neo-one-node-rpc-handler/src/createHandler.ts
- packages/neo-one-node-tools/bin/node-restore.js
- packages/neo-one-node-tools/gulpfile.js
- packages/neo-one-node-tools/package.json
- packages/neo-one-node-tools/src/bin/node-restore.ts
- packages/neo-one-node-tools/src/cmd.ts
- packages/neo-one-node-tools/src/restore.ts
- packages/neo-one-node-tools/tsconfig.json
- packages/neo-one-node/src/startFullNode.ts
- rush.json
- scripts/DockerfileNodeGSUtil
adds a package/script to the node image for restoring the leveldb properly when deployed. `gsutil rsync` doesn't work because the leveldb files are constantly changed, meaning it thinks it always needs to sync.  Our script checks the `mtime` of the `LOG` file in both places and uses that to determine if we should sync.
Also uses new ts `import type` features to quarantine opencensus and stop it from leaking memory in the node.
> feat(node): restore script / opencensus dynamic import

- packages/neo-one-website/tutorial/tutorial.md
Fixes a typo in the website tutorial [here](https://neo-one.io/tutorial). Search for "HellowWorld".
> fix(typo): fix typo in website tutorial

- common/changes/@neo-one/cli/compiler_2020-04-13-22-53.json
- packages/neo-one-cli/src/cmd/compile.ts
- packages/neo-one-cli/src/cmd/index.ts
- packages/neo-one-cli/src/compile/compileContract.ts
- packages/neo-one-cli/src/compile/createTasks.ts
- packages/neo-one-cli/src/compile/findContracts.ts
- packages/neo-one-cli/src/compile/index.ts
- packages/neo-one-cli/src/compile/writeContract.ts
Adds support for outputting compiled contract information to file. The new cli command is `compile` and has 2 flags `--path` the directory of source contracts and `--outDir` to output.
You can test this by running
```
rush build
node packages/neo-one-cli/bin/neo-one compile --path <testContractDir> --outDir ./testDir
```
there are example contract projects in the `__data__` folder of `neo-one-cli`.
Right now we just output the result of our compilation to a `.json` file but we could change the format of the output depending on what the community needs.
Should make the typescript compiler more usable for third parties that don't require the entire `neo-one` suite.
> feat(compiler): add support for outputting compiled contracts

- packages/neo-one-build-tools/src/utils.ts
simple hotfix to ignore ec-key name transform when packing for different versions
> fix(build): ignore transforming ec-key package in other format releases

- packages/neo-one-client-common/src/models/types.ts
- packages/neo-one-client-core/src/provider/convert.ts
The first two contracts published to the neo blockchain have a slightly different structure since they were preview versions.  See, the first two contracts here: https://neotracker.io/browse/contract/10 .
Created a special case which converts the preview contract into a standard ContractJSON format.  This should allow the scraper on neotracker to properly scrape these contracts.
Tested the getBlock method on the blocks which contain the preview contract publishes on blocks: 1,107,681 and 917083.
> fix(bug): NEODataProvider with Agency preview contracts

- packages/neo-one-website/docs/1-main-concepts/12-deployment.md
Go to https://neo-one.io/docs/deployment and see the "Upgrade" section. We _say_ that the `approveUpgrade` method has to be a `protected` method. But in the code example the `approveUpgrade` method is a `public` method. I think this should say `public` method so as to avoid confusion.
Someone should make sure I'm correct here before merging.
> fix(docs): fix slight mismatch in deploy doc

- common/config/rush/yarn.lock
- packages/neo-one-client-full-core/src/__tests__/__snapshots__/Client.test.ts.snap
- packages/neo-one-logger/src/loggers.ts
- packages/neo-one-node-tools/src/restore.ts
- packages/neo-one-smart-contract-codegen/src/__tests__/abi/__snapshots__/genABI.test.ts.snap
Just ran `rush update --full` in order to bump dependencies and to fix the `caniuse-lite` error we were seeing with `rush build`.
There's still some failing tests to be aware of:
- Cypress is failing due to Frag's node changes
- One unit test in `blockchain.test.ts` is failing due to Frag's node upgrade
Both will be fixed with upgrades to the DataProvider and that will be fixed as we finish integrating the C# node.
See CI checks pass except the ones mentioned above.
None.
Passing CI checks, upgraded deps.
Unknown issues with upgraded dependencies.
> chore(deps): rush update --full to fix caniuse-lite, etc

- packages/neo-one-cli-common-node/src/configuration.ts
- packages/neo-one-cli/src/cmd/start/neotracker.ts
- packages/neo-one-client-common/src/types.ts
- packages/neo-one-client-core/src/DeveloperClient.ts
- packages/neo-one-website/docs/1-main-concepts/10-testing.md
- packages/neo-one-website/docs/2-advanced-guides/09-configuration-options.md
Just changes any reference to "NEO tracker" to the correct "NEO Tracker" to keep NEO Tracker branding consistent.
> fix(nit): NEO tracker to NEO Tracker

- common/changes/@neo-one/cli-common-node/update-networks_2020-05-27-22-10.json
- packages/neo-one-cli-common-node/src/networks.ts
fixes #2033 
new default networks are `main` \ `test` \ `local` for neotracker.io/rpc, testnet.neotracker.io/rpc, localhost:9040 respectively.
> fix(cli): change default network paths to neotracker/local

- .circleci/config.yml
- packages/neo-one-smart-contract-codegen/src/__tests__/__snapshots__/genCommonBrowserFiles.test.ts.snap
- packages/neo-one-smart-contract-codegen/src/__tests__/__snapshots__/genCommonFiles.test.ts.snap
- packages/neo-one-smart-contract-codegen/src/__tests__/contracts/__snapshots__/genContracts.test.ts.snap
fixup snapshots that weren't updated from #2053
Also, the CI test path pattern has been wrong for awhile now, because of the difference in glob patterns `__tests__/**/*.test.ts` resolved to *ONLY* paths that were 1 folder after `__tests__` (d'oh!)
> fix(docs): fixup test snapshots / update CI glob path

- packages/neo-one-smart-contract-compiler/src/__tests__/compile/builtins/contract/blockchain.test.ts
This is just a test case that needed to be updated after the changes Frag made. InvocationTransactions only had 3 attributes before but now with the recent changes it looks like that has changed to 4. I suspect this is because we didn't need one of the attributes when using just our node solution but the NEOProvider does so it makes more sense to update the whole model.
I tested this externally as well to see how many attributes a simple transaction had using the `HelloWorld` contract and it is definitely 4.
> fix(CI): update blockchain.test.ts

- packages/neo-one-cli/src/cmd/compile.ts
- packages/neo-one-cli/src/cmd/convert/index.ts
- packages/neo-one-cli/src/cmd/new/index.ts
- packages/neo-one-cli/src/cmd/start/index.ts
- packages/neo-one-cli/src/cmd/stop/index.ts
Just makes our CLI command descriptions use consistent and correct grammar.
> fix(cli): make cli command info syntax consistent

- common/changes/@neo-one/cli-common-node/nits_2020-06-12-05-42.json
- common/changes/@neo-one/cli/nits_2020-06-12-05-42.json
- common/changes/@neo-one/client-common/nits_2020-06-12-05-42.json
- common/config/rush/command-line.json
- packages/neo-one-cli-common-node/src/configuration.ts
- packages/neo-one-cli/src/build/startNeotracker.ts
- packages/neo-one-client-common/src/types.ts
- packages/neo-one-website/docs/2-advanced-guides/09-configuration-options.md
Fixes minor issues I noticed while trying to use NEO•ONE and such. Like a broken link in our website docs, some documentation language cleanup, and setting `skip` to `true` by default.
None.
None.
Cleanup.
None.
#2061
> fix(nits): fix langauge nits, URL, skip NT to default true

- common/changes/@neo-one/cli/init-e2e_2020-06-16-23-17.json
- packages/neo-one-build-tests/environments/e2e/One.js
- packages/neo-one-build-tests/environments/e2e/jestSetup.js
- packages/neo-one-build-tests/environments/test/jestSetup.js
- packages/neo-one-build-tests/jest/e2e.js
- packages/neo-one-build-tools/types/e2e.d.ts
- packages/neo-one-cli/src/__e2e__/cmd/init.test.ts
Adds E2E tests for `neo-one init` command. Basically just pulls everything from #1705, which was created pre-RushJS, and makes it work with the current NEO•ONE and RushJS setup.
`rush e2e -t packages/neo-one-cli/src/__e2e__/cmd/init.test.ts`
None.
E2E test for init command.
None.
#1682 
#1705
> feat(e2e): add init e2e tests

- common/config/rush/yarn.lock
- packages/neo-one-build-tools-web/src/runCypress.ts
- packages/neo-one-local-browser-worker/package.json
- packages/neo-one-local-browser/package.json
- packages/neo-one-website/src/utils/getReferences.ts
- packages/neo-one-website/static.config.js
The website courses seem to have broken at commit `0b2422d`, even when retroactively adding the new post-install RushJS script, which removes all NPM installed `@neo-one` packages (except EC-Key). After adding a TON of logging to try to figure out where the `client.transfer()` was going wrong it seemed like an issue in node storage. So I looked at changelogs of packages like `pouchdb`, `level`, `level-js`, and `levelup`. I pinned those dependencies and that seemed to fix the storage issue in the node, in the website. So I narrowed it down to just `pouchdb`, which seems to have fixed the `client.transfer()` error. There's a whole saga of logs and trial/error behind this. But this fixes the website, so for now, we're good to go. Will open an issue to look more closely at this later, …
> fix(website): pin pouchdb, update two configs to make website work

- common/changes/@neo-one/cli-common-node/fix-helper_2020-07-07-04-21.json
- common/changes/@neo-one/cli/fix-helper_2020-07-07-04-21.json
- packages/neo-one-cli-common-node/src/networks.ts
- packages/neo-one-cli/src/index.ts
- packages/neo-one-website/docs/2-advanced-guides/09-configuration-options.md
Export the `createUserAccountProviderFunc` from `neo-one-cli-common-node` and `neo-one-cli` for use by users.
Update website documentation on how to use `createUserAccountProviderFunc` and how to create custom network definitions in `.neo-one.config.ts`.
I think no tests are needed. But here's how the docs look in the website:
None.
Easier network creation for users.
I'm not sure why we didn't export that in the past and make it available to users, so there might be an unknown reason why we didn't do that already. But it seems to be okay to use. It's also a more advanced API and is unlikely to actually be used any anyone, so we may be just making things more confusing for users by adding this.
#2079
> fix(cli): update network docs and cli exports

- common/changes/@neo-one/smart-contract-compiler/fix-switch_2020-07-09-23-27.json
- packages/neo-one-smart-contract-compiler/src/__tests__/compile/statement/BreakStatementCompiler.test.ts
- packages/neo-one-smart-contract-compiler/src/__tests__/compile/statement/SwitchStatementCompiler.test.ts
- packages/neo-one-smart-contract-compiler/src/compile/statement/SwitchStatementCompiler.ts
Switch statements with a `break` statement were not working inside SmartContract methods. The `break` keyword, if inside a switch statement, would break out of the entire function and code after the switch statement would not run. I nailed this behavior down by looking at the unit tests in `SwitchStatementCompiler.test.ts`. In those tests we covered this case, and those tests pass. But the behavior changed slightly when inside a function scope. So I added a switch statement unit test that's called within a SmartContract method to recreate the issue described in #2016. That new test is added in this PR in `SwitchStatementCompiler.test.ts`.
I believe that the `InvokeSmartContractMethodHelper.ts` is the helper that is called for the method invocation. It's there that the `finallyPC` is set, …
> fix(compiler): fix switch statement inside SC invocations

- common/changes/@neo-one/smart-contract-compiler/fix-arraystorage_2020-07-16-02-18.json
- packages/neo-one-smart-contract-compiler/src/__tests__/compile/builtins/contract/arrayStorage.test.ts
- packages/neo-one-smart-contract-compiler/src/__tests__/compile/builtins/contract/mapStorage.test.ts
- packages/neo-one-smart-contract-compiler/src/__tests__/compile/builtins/contract/setStorage.test.ts
- packages/neo-one-smart-contract-compiler/src/__tests__/compile/expression/ArrayLiteralExpressionCompiler.test.ts
- packages/neo-one-smart-contract-compiler/src/__tests__/compile/expression/ElementAccessExpressionCompiler.test.ts
- packages/neo-one-smart-contract-compiler/src/compile/builtins/contract/arrayStorage/pop.ts
- packages/neo-one-smart-contract-compiler/src/compile/builtins/contract/arrayStorage/push.ts
- packages/neo-one-smart-contract-compiler/src/compile/builtins/contract/mapStorage/get.ts
- packages/neo-one-smart-contract-compiler/src/compile/builtins/contract/mapStorage/set.ts
- packages/neo-one-smart-contract-compiler/src/compile/builtins/contract/setStorage/add.ts
- packages/neo-one-smart-contract-compiler/src/compile/builtins/contract/storage/at.ts
- packages/neo-one-smart-contract-compiler/src/compile/builtins/contract/storage/delete.ts
- packages/neo-one-smart-contract-compiler/src/compile/builtins/contract/storage/has.ts
- packages/neo-one-smart-contract-compiler/src/compile/expression/ElementAccessExpressionCompiler.ts
- packages/neo-one-smart-contract-compiler/src/compile/helper/createHelpers.ts
- packages/neo-one-smart-contract-compiler/src/compile/helper/types/number/CoerceToIntHelper.ts
- packages/neo-one-smart-contract-compiler/src/compile/helper/types/number/index.ts
Fixes #2016.
I poked around for several days learning the nature of the problem. And realized that index values between 1 and 15 (inclusive) would have no issues whether the index was computed or hardcoded, because when 1-15 are used as hardcoded values they are pushed onto the stack as `IntegerStackItem`s. But 0 and 16+ are pushed onto the stack as `BufferStackItem`s. But then ANY computed value is computed and then pushed onto the stack as `IntegerStackItem`s, no matter what value. Thus I needed to find a way to either make all `ArrayStorage` index values be Buffers or all be Integers. You can see in the section below that I initially tried to coerce all index values to Buffers but came up short. It then struck me that I could just add 0 to every index value before getting/setting in …
> fix(compiler): fix number mismatches in SetStorage, ArrayStorage, MapStorage

- packages/neo-one-smart-contract-compiler/src/__tests__/compile/builtins/contract/blockchain.test.ts
Temporary fix for #2102
Tested locally. `attributes.length` is always either 3 or 4. So any number outside of that should rightfully fail the test until we fix it more permanently.
None.
Passing test.
Looser coverage.
#2102
> fix(test): hot fix failing blockchain compiler test

- common/changes/@neo-one/cli/nt-update_2020-07-20-19-17.json
- common/config/rush/yarn.lock
- packages/neo-one-cli/package.json
- packages/neo-one-cli/src/__e2e__/cmd/start/neotracker.test.ts
- packages/neo-one-cli/src/__e2e__/cmd/stop/neotracker.test.ts
- packages/neo-one-cli/src/cmd/start/neotracker.ts
- rush.json
Update neotracker dependency to 1.4.1 to get rid of any traces of opencensus and to keep NT up to date in our E2E tests. Makes NT E2E tests work again.
- `rush e2e -t neotracker`
- CI checks
We tried a few things to essentially simulate neotracker being a part of this monorepo but everything hit a wall one way or another whether it be dependency resolution or problems rush encountered during its linking when I attempted to just create the correct `@neo-one` symlinks for neotracker myself.
opencensus should never creep up again
we are going back to NOT deleting the `@neo-one` dependencies post-install, let neotracker do whatever its going to do in practice it should resolve to whatever version of `@neo-one` the user has installed (which could cause its own problems down the line since we …
> fix(tests): update NT dep and website build process

- .huskyrc.js
Running `rush install` every checkout seems excessive. So we're removing it.
It works.
None.
Quicker development env.
Don't forget to `rush install` when necessary.
> fix(husky): remove checkout hook

- .github/workflows/website.yaml
- common/config/rush/command-line.json
- cypress/plugins/index.js
- cypress/tsconfig.json
- packages/neo-one-build-tools-web/src/webpack/plugin/node.tsx
Changes how we build the website and test the website by changing module resolution paths instead of copying `node_modules` to root.
Cypress should pass in CI.
None.
Simpler, quicker website builds/tests.
None.
> fix(cypress): fix web build process and cypress

- common/changes/@neo-one/client-core/node-debug_2020-07-14-23-23.json
- common/changes/@neo-one/node-core/node-debug_2020-07-14-23-23.json
- common/changes/@neo-one/node-protocol/node-debug_2020-07-14-23-23.json
- common/changes/@neo-one/node-rpc-handler/node-debug_2020-07-14-23-23.json
- common/changes/@neo-one/smart-contract-compiler/node-debug_2020-07-14-23-23.json
- packages/neo-one-client-core/src/provider/DataProviderBase.ts
- packages/neo-one-client-core/src/provider/JSONRPCClient.ts
- packages/neo-one-client-core/src/provider/NEODataProvider.ts
- packages/neo-one-client-core/src/provider/NEOONEDataProvider.ts
- packages/neo-one-client-core/src/provider/ProviderBase.ts
- packages/neo-one-client-core/src/user/LocalUserAccountProvider.ts
- packages/neo-one-node-core/src/Node.ts
- packages/neo-one-node-protocol/src/Node.ts
- packages/neo-one-node-protocol/src/errors.ts
- packages/neo-one-node-rpc-handler/src/createHandler.ts
`@receive` tagged invocation transactions were not able to be verified by other non-NEO•ONE nodes on the testnet. While this problem could be affecting other transaction types this is the only known issue. 
After comparing the transaction we create with the transaction `neon-js` creates I was able to see the differences in the transactions, namely that our transaction attached and relayed an additional verification script along with several other attributes that weren't accepted using the neon-js API.
Since we don't want to spend all of our time looking at a Neo 2.x issue that will undoubtedly get changed in the Neo 3.x migration this is a hotfix. Because of how the NEO•ONE node handles test invocations we create a new function called `relayStrippedTransaction` which takes in 2 invocation …
> fix(node): fix 'receive' invocations when relaying transactions to a live network

- common/changes/@neo-one/cli/migration-ts-fix_2020-07-22-20-43.json
- packages/neo-one-cli/src/common/load.ts
#2090 
Migration files saved as typescript were not working because of a ts-node register call when loading them. This removes that register call which fixes everything.
Its not completely clear to me what was happening but the ts error:
```
mart-contract/migration.ts:3:28 - error TS7006: Parameter '_a' implicitly has an 'any' type.
3 module.exports = function (_a, _network) {
~~
smart-contract/migration.ts:3:32 - error TS7006: Parameter '_network' implicitly has an 'any' type.
3 module.exports = function (_a, _network) {
~~~~~~~~
","stack":"TSError: ⨯ Unable to compile TypeScript:
smart-contract/migration.ts:3:28 - error TS7006: Parameter '_a' implicitly has an 'any' type.
3 module.exports = function (_a, _network) {
~~
smart-contract/migration.ts:3:32 - error TS7006: Parameter …
```
> fix(cli): migration.ts fix

- common/changes/@neo-one/node-storage-levelup/fix-web_2020-07-27-19-51.json
- common/changes/@neo-one/node/fix-web_2020-07-27-19-51.json
- common/changes/@neo-one/smart-contract-compiler/fix-web_2020-07-27-19-51.json
- common/config/rush/yarn.lock
- packages/neo-one-node-browser/package.json
- packages/neo-one-node-storage-levelup/package.json
- packages/neo-one-node/package.json
- packages/neo-one-smart-contract-compiler/package.json
There seems to be some issue with using `LevelUp`/`Level-JS`/`PouchDB` for node storage, but which only appears in the website courses. Pinning these dependencies fixes it, so we'll go with that hot fix now until we have time to investigate later.
Works locally. Make sure it passes CI checks.
None.
Website courses working.
None.
None.
> fix(website): pin level-js and levelup for web courses issue

- packages/neo-one-client-common/src/GasToken.ts
- packages/neo-one-client-common/src/NativeContract.ts
- packages/neo-one-client-common/src/NeoToken.ts
- packages/neo-one-client-common/src/PolicyContract.ts
- packages/neo-one-client-common/src/index.ts
- packages/neo-one-client-common/src/models/types.ts
- packages/neo-one-client-common/src/types.ts
- packages/neo-one-csharp-core/package.json
- packages/neo-one-csharp-core/src/Node.ts
- packages/neo-one-csharp-core/src/TransactionData.ts
- packages/neo-one-csharp-core/src/index.ts
- packages/neo-one-csharp-core/src/transaction/Transaction.ts
- packages/neo-one-node-blockchain/src/Blockchain.ts
- packages/neo-one-node-blockchain/src/__tests__/Blockchain.test.ts
- packages/neo-one-node-core/src/TransactionData.ts
- packages/neo-one-node-core/src/index.ts
- packages/neo-one-node-core/src/transaction/Transaction.ts
- packages/neo-one-node-protocol/src/Node.ts
- packages/neo-one-node-rpc-handler/src/createHandler.ts
First round of RPC server method updates. All the methods from `neo-project/neo-modules` are here but not all are implemented or finished. Note we also have RPC methods that are unique to NEO•ONE. Those have largely stayed the same or they are noted where they will need extra work.
Here are the methods that still need work/consideration:
- invokescript
- Implemented just fine, but needs to be tested
- getnetworksettings
- Unique to NEO•ONE
- getinvocationdata
- Unique to NEO•ONE
- Need to implement serializeJSONWithInvocationData() in Transaction.ts
- Maybe remove or change name depending on data storage changes
- relaytransaction
- NEO•ONE
- relaystrippedtransaction
- NEO•ONE
- getclaimamount
- NEO•ONE
- Need to figure out how we’re going to implement calculateClaimAmount in Blockchain
- …
> feat(rpc): first round of RPC updates

- packages/neo-one-node-core/src/StackItems/PrimitiveStackItemBase.ts
- packages/neo-one-node-vm/lib/Dispatcher.cs
- packages/neo-one-node-vm/lib/Dispatcher.csproj
- packages/neo-one-node-vm/lib/ReturnHelpers.cs
- packages/neo-one-node-vm/package.json
- packages/neo-one-node-vm/src/Dispatcher.ts
- packages/neo-one-node-vm/src/Methods/BaseMethods.ts
- packages/neo-one-node-vm/src/__tests__/Dispatcher.test.ts
- packages/neo-one-node-vm/src/errors.ts
- packages/neo-one-node-vm/src/index.ts
- packages/neo-one-node-vm/src/utils.ts
- packages/neo-one-node/src/startFullNode.ts
Adds the ability to pass an optional `protocolSettings` option into the Dispatcher, which will initialize the NeoVM with those settings. These settings are things like `millisecondsPerBlock`, validators, etc.
`rush test -t packages/neo-one-node-vm/src/__tests__/Dispatcher.test.ts`
None.
Closer to Neo3
None.
#2009
#2161
> feat(vm): add ability to pass protocol settings into vm

- packages/neo-one-client-common/src/models/nep5/Nep5BalanceKeyModel.ts
- packages/neo-one-client-common/src/models/nep5/Nep5TransferKeyModel.ts
- packages/neo-one-node-blockchain/src/Blockchain.ts
- packages/neo-one-node-blockchain/src/getNep5UpdateOptions.ts
- packages/neo-one-node-core/src/Nep5TransferKey.ts
- packages/neo-one-node-core/src/StackItems/ByteStringStackItem.ts
- packages/neo-one-node-core/src/StackItems/IntegerStackItem.ts
- packages/neo-one-node-core/src/manifest/ContractPermissionDescriptor.ts
- packages/neo-one-node-core/src/utils/deserializeStackItem.ts
- packages/neo-one-node-native/src/NEOToken.ts
- packages/neo-one-node-protocol/src/Node.ts
- packages/neo-one-node-rpc-handler/src/createHandler.ts
- packages/neo-one-node-storage-common/src/keys.ts
- packages/neo-one-node-vm/src/converters/stackItems.ts
- packages/neo-one-node/src/__tests__/blockchain.test.ts
getunclaimed, getnep5transfers, getnep5balances all had some issues.
- fixed `calculateBonus` method not using Integer division like it was supposed to (Math.floor(...)).
- fixed nep5balance storage using `writeVarBytesLE` to the correct `writeUInt160`
- fixed getNep5Transfers not using the provided scriptHash in its storage search.
- adjusts the block request rate in the node, hopefully increases stability.
- fixed `IntegerStackItem` not using 'le' for its BN representation.
- syntax nits
fixes #2204
> fix(node): fixup RPC methods

- packages/neo-one-node-rpc-handler/src/createHandler.ts
Fixes RPC method `getnep5transfers`, which was returning the wrong data for `received`.
Also gets closer to the C# input and return formats. Addresses in transfer objects should be base58 addresses instead of hex addresses. And inputs should take a scriptHash or base58 address.
This PR also includes a limit for `getAllStorage` RPC method for Native contracts.
Was tested manually with Postman to compare against Neo TestNet node results. Will also be tested more thoroughly with unit tests later.
None.
Closer to Neo3. Fixes bug.
None.
#2009 #1882
> fix(rpc): fix rpc getnep5transfers method for received

- packages/neo-one-client-common/src/models/types.ts
- packages/neo-one-client-core/src/__tests__/provider/temp.test.ts
- packages/neo-one-node-rpc-handler/src/createHandler.ts
- packages/neo-one-node-vm/lib/Dispatcher.Engine.cs
Makes `invokescript` RPC method work properly and return proper formats.
Tested with Postman and unit test.
None.
Correct RPC method, closer to Neo3.
None.
#2176 
#2009
> fix(rpc): fix invokescript method

- packages/neo-one-cli/src/compile/interop.ts
- packages/neo-one-cli/src/console/startConsole.ts
- packages/neo-one-cli/src/deploy/runMigration.ts
- packages/neo-one-client-common/src/models/types.ts
- packages/neo-one-client-common/src/types.ts
- packages/neo-one-client-core/src/__tests__/provider/sendrawtransaction.test.ts
- packages/neo-one-client-core/src/args.ts
- packages/neo-one-client-core/src/nep5.ts
- packages/neo-one-client-core/src/provider/JSONRPCClient.ts
- packages/neo-one-client-core/src/provider/NEOONEDataProvider.ts
- packages/neo-one-client-core/src/provider/NEOONEProvider.ts
- packages/neo-one-client-core/src/provider/convert.ts
- packages/neo-one-client-core/src/user/LocalUserAccountProvider.ts
- packages/neo-one-client-core/src/user/UserAccountProviderBase.ts
Fix up more Client APIs and related types. Especially in `NEOONEDataProvider` and `NEOONEProvider`.
Note that I removed `getInvocationData` and `iterActionsRaw` from the data provider/provider but kept the converters and types around in case we want to come back to them. I’m not sure where those were used or if they have any downstream affects in the Client. Figured we’d come back to them after finishing all this to start adding back functionality like “invocation data”.
Added getApplicationLogData.
None. TBD in final e2e testing.
None.
Closer to Neo3.
None.
#2218 
#2009
> fix(client): fix more client apis

- common/config/rush/command-line.json
- packages/neo-one-editor-server/src/resolveMiddleware.ts
rush deployment script for the website was outdated. Also a middleware had a syntax error that was stopping it from compiling.
> fix(web): fix website deployment script

- packages/neo-one-client-core/src/user/keystore/HDKeyStore.ts
Add types to `HDKeystore` so that it build for next/esm.
> fix(keystore): add types necessary to build for esm/next

- packages/neo-one-cli-common-node/src/configuration.ts
- packages/neo-one-website/docs/2-advanced-guides/09-configuration-options.md
Fixes small error when generating a config file in a typescript environment. Migration file would be `.js` regardless of language. Now it will be `.ts` when it detects typescript.
None.
None.
Better usability.
None.
None.
> fix(cli): fix migration file path for typescript

- common/changes/@neo-one/node-vm/vm-env-fixup_2020-12-09-19-41.json
- packages/neo-one-node-vm/src/utils.ts
Add default environment variables for edge in the vm
adds a switch for the case of the package being exported.
> fix(vm): fixup environment variable requirements

- packages/neo-one-client-core/src/provider/convert.ts
- packages/neo-one-node-core/src/StackItems/StackItems.ts
title, edit to previous PR.
ByteStringStackItem should return a base64 encoded string on the node side and convert to ascii on the frontend.
> fix(node): fixup byteStringStackItem toJSON return value

- packages/neo-one-cli-common-node/src/configuration.ts
- packages/neo-one-cli-common-node/src/networks.ts
- packages/neo-one-cli-common/src/index.ts
- packages/neo-one-cli-common/src/rpcURL.ts
- packages/neo-one-cli/src/__data__/generateTests.ts
- packages/neo-one-cli/src/__data__/index.ts
- packages/neo-one-cli/src/__e2e__/cmd/generate.test.ts
- packages/neo-one-cli/src/build/deployContract.ts
- packages/neo-one-cli/src/cmd/compile.ts
- packages/neo-one-cli/src/cmd/console.ts
- packages/neo-one-cli/src/cmd/deploy.ts
- packages/neo-one-cli/src/cmd/generate.ts
- packages/neo-one-cli/src/cmd/index.ts
- packages/neo-one-cli/src/cmd/info.ts
- packages/neo-one-cli/src/cmd/init.ts
- packages/neo-one-cli/src/common/start.ts
- packages/neo-one-cli/src/compile/compileContract.ts
- packages/neo-one-cli/src/compile/createTasks.ts
- packages/neo-one-cli/src/generate/createTasks.ts
- packages/neo-one-cli/src/generate/index.ts
- packages/neo-one-node-protocol/src/Message.ts
- packages/neo-one-smart-contract-codegen/src/client/genBrowserClient.ts
This does multiple things to improve the CLI user experience.
1. Adds new `generate` command that will do some parts of the `build` command. It won't start a local development network but it will compile the contracts and generate the common code to integrate with dApps. This will help demonstrate more features are ready to go as we migrate to Neo3. This also provides another option for building the project without starting a dev network unnecessarily.
2. Adds an optional CLI argument to every command: `--configPath` which will override the search for a neo-one config file in the local directory and instead find it by the provided path. This is primarily for internal use as it makes it easier for us to test the CLI in a demo repo without having to publish to NPM.
3. It also does a little …
> feat(cli): add cli configpath option and do cli cleanup

- packages/neo-one-cli/CHANGELOG.json
- packages/neo-one-cli/package.json
- packages/neo-one-smart-contract-test/package.json
Bump one more package to 3.1.0- smart-contract-test.
> fix(release): bump smart-contract-test version

- packages/neo-one-website/src/components/reference/TypeFilter.tsx
Select component in TypeFilter.ts did not persist the selection of type (it only displays placeholder text regardless). This change alters the component slightly to display the selected type inside to confirm to users what was selected.
Before:
After:
Tested locally
Currently no alternate design
Improved UI.
None currently.
None.
> Fix: type filter selection

- packages/neo-one-client-switch/src/node/createConsoleLogMessages.ts
- packages/neo-one-client-switch/src/node/initializeSourceMap.ts
- packages/neo-one-client-switch/src/node/processActionsAndMessage.ts
- packages/neo-one-client-switch/src/node/processConsoleLogMessages.ts
Changed neo-one-client-switch/src/node to mirror ../src/browser due to issue with source map initialization when running tests with Jest.
Followed the installation steps in neo-one's tutorial to set up the environment and get the required packages to develop and test smart contract. Errors were thrown when running smart contract tests as shown below:
Console traced down Jest uses cjs/node.
I made changes to the compiled js in cjs/node folder to mirror that of cjs/browser and smart contract tests passed normally.
None
Eliminate issues that developers might run into when testing smart contracts locally.
N/A
N/A
> fix: client-switch source map initialization issue with Jest

- packages/neo-one-node-vm/src/opcodes.ts
- packages/neo-one-node-vm/src/stackItem/ArrayStackItem.ts
- packages/neo-one-node-vm/src/stackItem/MapStackItem.ts
- packages/neo-one-node-vm/src/stackItem/StackItemBase.ts
- packages/neo-one-node-vm/src/stackItem/StructStackItem.ts
Revert the changes made to the VM in #2293. That PR was made to try to fix some VM inconsistencies between NEO•ONE's v2 node and the official Neo node. But after recent review it seems that the better path is to keep our master-2.x branch "clean" in the sense that we don't want to put any breaking changes on that branch until ALL the inconsistencies are fixed. That way we can easily publish non-breaking versions of NEO•ONE for 2.x with updates, bug fixes, etc. while not breaking our node.
When we have time we can make all the necessary updates to the 2.x branch with all the node updates and thus all the breaking changes at once. Then we can reassure ourselves and our users the NEO•ONE 2.x works with Neo2.
I'll move these changes to a new PR to a new 2.x dev branch called …
> fix(revert): revert breaking VM changes. move to dev branch

- packages/neo-one-node-vm/src/opcodes.ts
- packages/neo-one-node-vm/src/stackItem/ArrayStackItem.ts
- packages/neo-one-node-vm/src/stackItem/MapStackItem.ts
- packages/neo-one-node-vm/src/stackItem/StackItemBase.ts
- packages/neo-one-node-vm/src/stackItem/StructStackItem.ts
Updates constraint that keys must be primitive stack item types in maps/structs in the VM. See here for when that was implemented in the NeoVM: https://github.com/neo-project/neo-vm/pull/28.
Originally implemented in #2293 and then revert from #2320. Never deployed to production nodes or published to NPM on master-2.x branch.
Tested originally in #2293.
None. Should have caught this earlier.
Works on updating our master-2.x branch to be more compatible with Neo2.
None.
None.
> fix(vm): keys must be primitive stack items

- packages/neo-one-smart-contract-compiler/src/utils/throwOnDiagnosticErrorOrWarning.ts
- packages/neo-one-ts-utils/src/class_.ts
- packages/neo-one-website/docs/0-installation/5-contract-mixins.md
Template support.
ts compiler ignored contracts that use mixins syntax.
```typescript
// ...imports
export class TestToken extends NEP5Token(SmartContract){
// ...
}
```
The issue came from the following code block: 
```typescript
if (clause === undefined || !ts.isHeritageClause(clause) || !heritage.isExtends(clause)) {
return acc;
}
```
The `NEP5Token(SmartContract)` is neither a HeritageClause nor an Extends clause. So a separate `if` seems necessary for the specific case of mixins.
1. symlink `neo-one-ts-utils`
2. use mixins syntax like above
3. run compile or build to see results
N/A
Able to compile contracts with mixins.
Might affect other syntaxes.
N/A
> fix(compiler, doc): mixin syntax fix and template doc.

- packages/neo-one-build-tests/environments/e2e/jestSetup.js
- packages/neo-one-build-tests/environments/test/jestSetup.js
- packages/neo-one-node-native/src/ContractManagement.ts
- packages/neo-one-node-native/src/GASToken.ts
- packages/neo-one-node-native/src/LedgerContract.ts
- packages/neo-one-node-native/src/NEOToken.ts
- packages/neo-one-node-native/src/NameService.ts
- packages/neo-one-node-native/src/NativeContract.ts
- packages/neo-one-node-native/src/OracleContract.ts
- packages/neo-one-node-native/src/Policy.ts
- packages/neo-one-node-native/src/RoleManagement.ts
- packages/neo-one-node-vm/lib/Dispatcher.Engine.cs
Fix how Native contract IDs are set. The mutable counter would keep values in between Jest tests and thus each test would initiate it's own blockchain with a new set of IDs which would end up wrong. Now we just hard-set them.
Tested locally.
None.
Tests working.
None.
None.
> fix(native): fix native contract ids

- common/config/rush/command-line.json
- packages/neo-one-build-tools-web/includes/now/package.json.now
- packages/neo-one-build-tools-web/includes/now/preview.now.json
- packages/neo-one-build-tools-web/includes/now/static.now.json
- packages/neo-one-build-tools-web/includes/now/testRunner.now.json
- packages/neo-one-build-tools-web/includes/vercel/preview.vercel.json
- packages/neo-one-build-tools-web/includes/vercel/server.vercel.json
- packages/neo-one-build-tools-web/includes/vercel/static.vercel.json
- packages/neo-one-build-tools-web/includes/vercel/testRunner.vercel.json
- packages/neo-one-editor-server/src/resolveMiddleware.ts
- Changed commands to deploy to Vercel using Vercel CLI. Also changed deploy configs to correctly deploy to target projects.
- Fixed 'unreachable code' error in a middleware during compilation. `ctx.throw()` already takes the execution path back to the entry file
- Removing `rush compile-all-live` from `deploy-all-live` command.
`deploy-static-live`, `deploy-preview-live`, `deploy-server-live`, and `deploy-test-runner-live` will deploy to preview as default.
-Run `rush deploy-static-live` [--prod]
It would be better if we can propagate or pass the flag `--prod` from `deploy-all-live` to all other deploy sub-commands. Like `rush deploy-all-live --prod`. Currently, rush only append `--prod` to the end of the command string so it would not apply to every commands.
---
---
- Deploy using …
> fix(rush, editor-server): fixed vercel deploy commands, configs, and editor-server middleware

- common/config/rush/command-line.json
- packages/neo-one-build-tools-web/includes/now/package.json.now
- packages/neo-one-build-tools-web/includes/now/preview.now.json
- packages/neo-one-build-tools-web/includes/now/static.now.json
- packages/neo-one-build-tools-web/includes/now/testRunner.now.json
- packages/neo-one-build-tools-web/includes/vercel/preview.vercel.json
- packages/neo-one-build-tools-web/includes/vercel/server.vercel.json
- packages/neo-one-build-tools-web/includes/vercel/static.vercel.json
- packages/neo-one-build-tools-web/includes/vercel/testRunner.vercel.json
- Changed commands to deploy to Vercel using Vercel CLI. Also changed deploy configs to correctly deploy to target projects.
- Removing `rush compile-all-live` from `deploy-all-live` command.
`deploy-static-live`, `deploy-preview-live`, `deploy-server-live`, and `deploy-test-runner-live` will deploy to preview as default.
-Run `rush deploy-static-live` [--prod]
It would be better if we can propagate or pass the flag `--prod` from `deploy-all-live` to all other deploy sub-commands. Like `rush deploy-all-live --prod`. Currently, rush only append `--prod` to the end of the command string so it would not apply to every commands.
---
---
- Deploy using commands
- Deploy either dist, server, preview, or testRunner.
N/A
N/A
> fix(rush): fixed Vercel deploy commands & configs

- README.md
- contributing.md
- packages/neo-one-node-blockchain/src/Blockchain.ts
- packages/neo-one-node-vm/lib/Dispatcher.Engine.cs
- packages/neo-one-node-vm/lib/Dispatcher.Snapshot.cs
- packages/neo-one-node-vm/lib/Dispatcher.cs
- packages/neo-one-node-vm/lib/ReturnHelpers.cs
- packages/neo-one-node-vm/src/__tests__/Dispatcher.test.ts
Makes more updates to the node and related packages for cleanup and compatibility with RC1:
- Allows us to pass in and get out all the ProtocolSettings to/from the dispatcher correctly, including NativeUpdateHistory.
- Reverts some methods in the dispatcher that were made public for debugging reasons and reverts them back to private methods.
- Updates the README to notify that master is a dev branch.
- Fixes Blockchain so it correctly updates the standby committee.
Tested in development.
None.
Bug fixes, cleanup.
None.
#2388
> fix(rc1): minor updates for more rc1 compatibility and cleanup

- packages/neo-one-smart-contract-compiler/src/compile/builtins/contract/NativeContractCallValue.ts
- packages/neo-one-smart-contract-compiler/src/compile/builtins/contract/block.ts
- packages/neo-one-smart-contract-compiler/src/compile/builtins/contract/blockchain.ts
- packages/neo-one-smart-contract-compiler/src/compile/builtins/contract/contract.ts
- packages/neo-one-smart-contract-compiler/src/compile/builtins/contract/linkedSmartContract/for.ts
- packages/neo-one-smart-contract-compiler/src/compile/builtins/contract/smartContract/destroy.ts
- packages/neo-one-smart-contract-compiler/src/compile/builtins/contract/smartContract/for.ts
- packages/neo-one-smart-contract-compiler/src/compile/builtins/contract/transaction.ts
- packages/neo-one-smart-contract-compiler/src/compile/helper/binary/BinaryDeserializeHelper.ts
- packages/neo-one-smart-contract-compiler/src/compile/helper/binary/BinarySerializeHelper.ts
- packages/neo-one-smart-contract-compiler/src/compile/helper/contract/IsCallerHelper.ts
- packages/neo-one-smart-contract-compiler/src/compile/helper/contract/UpgradeHelper.ts
- packages/neo-one-smart-contract-compiler/src/compile/helper/crypto/RIPEMD160Helper.ts
- packages/neo-one-smart-contract-compiler/src/compile/helper/crypto/SHA256Helper.ts
CallContract API changed.
added call flags before calling contracts.
tested locally.
N/A
N/A
Currently setting the call flags to `None`. Should check the correct type of flag to replace them.
N/A
> fix(compiler): CallFlags for calling native contract

- packages/neo-one-client-core/src/args.ts
- packages/neo-one-smart-contract-compiler/src/__data__/helpers/startNode.ts
- packages/neo-one-smart-contract-compiler/src/__tests__/compile/builtins/contract/contract.test.ts
- packages/neo-one-smart-contract-compiler/src/__tests__/compile/builtins/contract/transaction.test.ts
- packages/neo-one-smart-contract-compiler/src/compile/builtins/contract/manifest/index.ts
- packages/neo-one-smart-contract-compiler/src/compile/builtins/contract/manifest/parameterType.ts
- packages/neo-one-smart-contract-compiler/src/compile/builtins/contract/transaction.ts
- packages/neo-one-smart-contract/src/index.d.ts
- Adds `ContractParameterType` to compiler
- Updates manifest and transaction compiler tests
None.
None.
Compiler fixes.
None.
#2388
> fix(compiler): add paramtype to compiler and other fixes

- packages/neo-one-smart-contract-compiler/src/__tests__/compile/builtins/contract/block.test.ts
- packages/neo-one-smart-contract-compiler/src/__tests__/compile/builtins/contract/blockchain.test.ts
- packages/neo-one-smart-contract-compiler/src/__tests__/compile/builtins/contract/contract.test.ts
- packages/neo-one-smart-contract-compiler/src/__tests__/compile/builtins/contract/mapStorage.test.ts
- packages/neo-one-smart-contract-compiler/src/__tests__/compile/helper/contract/InvokeSmartContractHelper0.test.ts
- packages/neo-one-smart-contract-compiler/src/compile/builtins/contract/linkedSmartContract/for.ts
- packages/neo-one-smart-contract-compiler/src/compile/builtins/contract/manifest/parameter.ts
- packages/neo-one-smart-contract-compiler/src/compile/builtins/contract/smartContract/for.ts
- packages/neo-one-smart-contract-compiler/src/compile/helper/contract/HandleNormalHelper.ts
- packages/neo-one-smart-contract-compiler/src/compile/helper/types/UnwrapValRecursiveHelper.ts
- Fixes calling contract methods with a void return
- Fixes contract manifest compiler API tests
- Fixes contract params in compiler
- Removes `test.only`
None.
None.
Compiler fixes.
None.
#2388
> fix(compiler): fix calling contracts with void return and more

- packages/neo-one-client-common/src/models/vm.ts
- packages/neo-one-smart-contract-compiler/src/__tests__/compile/builtins/contract/arrayStorage.test.ts
- packages/neo-one-smart-contract-compiler/src/__tests__/compile/builtins/contract/mapStorage.test.ts
- packages/neo-one-smart-contract-compiler/src/compile/helper/createHelpers.ts
- packages/neo-one-smart-contract-compiler/src/compile/helper/map/IteratorToMapHelper.ts
- packages/neo-one-smart-contract-compiler/src/compile/helper/map/MapToNestedArrHelper.ts
- packages/neo-one-smart-contract-compiler/src/compile/helper/map/NestedArrToMapHelper.ts
- packages/neo-one-smart-contract-compiler/src/compile/helper/map/index.ts
- packages/neo-one-smart-contract-compiler/src/compile/helper/storage/IterStorageHelper.ts
- Replaces `System.Iterator.Concat` API with a workaround composed of new helpers: `MapToNestedArrHelper`, `NestedArrToMapHelper`, `IteratorToMapHelper`
- Removes old syscall APIs in the SysCall enum
- Adds `PRINT` opcode for good for now for easier debugging
- Splits up tests in `mapStorages.test.ts` and in `arrayStorage.test.ts` so that the test contract doesn't exceed the max transaction script size
- Adds tests in `mapStorage.test.ts`, `arrayStorage.test.ts` to cover corner cases described in Possible Drawbacks below.
- `mapStorage.test.ts`
- `arrayStorage.test.ts`
None.
Gets compiler to compile when iterating over structured storage.
Possibly unforeseen or untested consequences to this change. Seems good enough for now though. The one main potential issue is overlapping keys when …
> fix(compiler): replace iter.concat api and more

- packages/neo-one-smart-contract-compiler/src/compile/helper/storage/ForEachStructuredStorageBaseHelper.ts
- Fix `pushValue` option in `ForEachStructuredStorage`
Before this fix there was an extra `undefined` (internal representation of undefined) being pushed to the stack unnecessarily when using the `for...of` statement with structured storage items. This caused the eventual return stack to have a stack size of 1 instead of stack size of 0 and was throwing an error when it finally hit `RET`. Before this fix `option.pushValue` was always `true`. Now it should be `false` for structured storage items.
- `arrayStorage.test.ts`
- `mapStorage.test.ts`
- `setStorage.test.ts`
None.
Accurate return stacks.
It's possible that this is the wrong fix. I couldn't recreate the issue on the master-2.x branch because of unrelated problems. Being able to do that would have allowed me greater insight into what …
> fix(compiler): structured storage foreach pushvalue fix

- packages/neo-one-smart-contract-compiler/src/contract/ContractInfoProcessor.ts
- Makes the deploy method not marked as "safe" since it requires to read and write storage
- `arrayStorage.test.ts`
None.
Can now call `deploy` method from other contracts without worrying about callflags.
This could be a problem later on, but ignoring for now. Need to ultimately check and understand the safe method marker.
#2388
> fix(compiler): fix deploy method safety to not modify callflags

- packages/neo-one-smart-contract-compiler/src/compile/builtins/contract/linkedSmartContract/for.ts
- packages/neo-one-smart-contract-compiler/src/compile/builtins/contract/smartContract/for.ts
- packages/neo-one-smart-contract-compiler/src/compile/helper/global/CreateGlobalObjectHelper.ts
- Fixes left over changes needed from previous commit which changed/fixed how contracts are called
- This applies those changes to linked smart contracts
- Also fixes a previously not considered case where a method would be called with no arguments. This fix is made in `CreateGlobalObjectHelper`
Run any compiler test that called a method on another contract.
None.
Correctly call linked smart contracts.
Possible unforeseen corner cases with `CreateGlobalObjectHelper`.
#2388
> fix(compiler): fixup how linked smart contracts are called

- packages/neo-one-client-common/src/common.ts
- packages/neo-one-node-core/src/StackItems/MapStackItem.ts
- packages/neo-one-smart-contract-compiler/src/compile/helper/common/SliceKeyHelper.ts
- packages/neo-one-smart-contract-compiler/src/compile/helper/common/index.ts
- packages/neo-one-smart-contract-compiler/src/compile/helper/createHelpers.ts
- packages/neo-one-smart-contract-compiler/src/compile/helper/storage/DeleteStorageBaseHelper.ts
- packages/neo-one-smart-contract-compiler/src/compile/helper/storage/GetStorageHelper.ts
- packages/neo-one-smart-contract-compiler/src/compile/helper/storage/PutStorageHelper.ts
- Adds `SliceKeyHelper` to compiler as a quick fix for when keys are too large in map stack items. This problem primarily occurs when a user is trying to use MapStorage with a key which is an array of items like addresses, which is a common use case that we promote in our templates and tutorials. This is a temporary fix as it's not an ideal solution.
Note that it breaks some other APIs like iterating through Set and Map storage keys and breaks the `.at()` method for both as well. Possibly breaks other APIs as well.
- `mapStorage.test.ts`
- `TestToken.test.ts`
None for now.
NEP17 template working as written.
Possibly breaks other APIs and introduces unforeseen bugs.
#2388
> fix(compiler): quick fix for key too large error

- packages/neo-one-node-vm/lib/Dispatcher.csproj
- packages/neo-one-node-vm/lib/ReturnHelpers.cs
Update dispatcher to correctly account for Buffer stack item returns.
Tested on node bug found while deploying RC3 node. Works.
None.
No bug.
None.
#2410
> fix(node): update distpacher stack item return

- packages/neo-one-cli-common-node/package.json
- packages/neo-one-cli-common-node/src/configuration.ts
- packages/neo-one-website/docs/0-installation/0-quick-start.md
- packages/neo-one-website/tutorial/tutorial.md
- Updates how we resolve paths before writing them to the final config file so that those paths will work on Windows and Unix platforms. This came up when users on Windows would try `neo-one build` and would get an error when it tried to start the development network. What was happening was it was using `fs.ensureDir()` on a file path that had `\n` in it from `.neo-one\network` (on Windows) which is obviously a newline character on Windows and thus was trying to run `mkdir` on an invalid path. By normalizing the paths we still write `.neo-one/network` even on Windows. But Windows will still use this as a valid path without reading a newline character.
- Also makes minor fixes to the website docs
Tested manually in a neo-one project on macOS and Windows 10.
None.
NEO•ONE works on Windows. …
> fix(cli): fix config on windows and website

- packages/neo-one-client/package.json
- packages/neo-one-client/src/index.ts
See title.
- `rush build -t @neo-one/developer-tools`
- `rush build -t @neo-one/client`
None.
Dev tools back in client package.
None.
#2198
> fix(client): add back dev-tools

- packages/neo-one-cli/src/cmd/start/neotracker.ts
- packages/neo-one-smart-contract-compiler/src/compile/expression/ElementAccessExpressionCompiler.ts
Add an error thrown when a user tries to use the CLI command `neo-one start neotracker`, which isn't implemented yet.
None.
None.
Best UX.
None.
#2428
> fix(cli): remove nt feature from n3 cli

- packages/neo-one-cli/src/compile/writeContract.ts
- Updates debug output for v1.2 of Neo Debug Info Spec.
None.
None.
Fits Neo Debug Spec.
The new `static-variables` output is not tied to the programmatic output of the compiler. It's hard-coded to the correct output (for now). Thus the use of static variable slots could change in our compiler down the line and the updater would have to remember to update this debugger output.
#2451
> feat(cli): update debugger output for v1.2 of neo debug spec

- packages/neo-one-node-core/src/Signer.ts
- packages/neo-one-node-protocol/src/Message.ts
- packages/neo-one-node-protocol/src/Node.ts
- Fixes a simple JS function binding bug that was very difficult to find due to logging P2P errors.
- Adds a simple log to catch this type of thing more easily in the future.
Continued node sync locally works.
The new logging in `MessageTransform` can and should be better but didn't have time to work that in correctly now and just added a `console.log`.
Node working. And better error logging.
None.
#2480 
#2410
> fix(node): fix p2p error and add logging

- packages/neo-one-cli-common-node/src/networks.ts
- packages/neo-one-cli-common/src/rpcURL.ts
- packages/neo-one-cli/src/__e2e__/cmd/compile.test.ts
- packages/neo-one-cli/src/generate/createTasks.ts
- packages/neo-one-node-protocol/src/Node.ts
- packages/neo-one-website/docs/0-installation/0-quick-start.md
- packages/neo-one-website/docs/0-installation/2-environment-setup.md
- packages/neo-one-website/docs/2-advanced-guides/08-configuration-options.md
- packages/neo-one-website/tutorial/tutorial.md
- Update some N3 docs
- Update and fix some client/cli settings
- Add back `info` logging when persisting blocks
None.
None.
Better docs and UX.
None.
#2410
> fix(docs,cli): fixup some docs and client settings

- packages/neo-one-client-common/src/common.ts
- packages/neo-one-client-full-common/src/__data__/models.ts
- packages/neo-one-client-full-common/src/models/manifest/ContractPermissionDescriptorModel.ts
- packages/neo-one-smart-contract-compiler/src/compile/getSmartContractInfo.ts
- packages/neo-one-smart-contract-compiler/src/contract/ManifestSmartContractProcessor.ts
- packages/neo-one-smart-contract-compiler/src/contract/getContractProperties.ts
- Fixes #2479
Not tested.
None.
The `trusts` property is now properly parsed for the correct client format.
Not thoroughly tested. Could lead to compiler errors.
#2479 
#2410
> fix(compiler): fix parsing/validation of trusts array in contract props

- packages/neo-one-cli/src/__data__/buildTests.ts
- packages/neo-one-cli/src/__data__/generateTests.ts
- packages/neo-one-cli/src/compile/compileContract.ts
- packages/neo-one-cli/src/compile/interop.ts
- packages/neo-one-cli/src/compile/writeContract.ts
- packages/neo-one-cli/src/deploy/actionResult.ts
- packages/neo-one-client-common/src/contractParameters.ts
- packages/neo-one-client-core/src/args.ts
- packages/neo-one-client-core/src/sc/common.ts
- packages/neo-one-client-core/src/sc/createSmartContract.ts
- packages/neo-one-client-switch/src/common/createConsoleLogMessages.ts
- packages/neo-one-smart-contract-compiler/src/__data__/snippets/semantic/single/complex.ts
- packages/neo-one-smart-contract-compiler/src/__data__/snippets/semantic/single/valid.ts
- packages/neo-one-smart-contract-compiler/src/compile/builtins/contract/createEventNotifier.ts
- packages/neo-one-smart-contract-lib/src/ICO.ts
- packages/neo-one-smart-contract-test/src/__tests__/TestICO.test.ts
- packages/neo-one-smart-contract-test/src/__tests__/__snapshots__/TestICO.test.ts.snap
- packages/neo-one-website/docs/1-main-concepts/03-standard-library.md
- packages/neo-one-website/docs/1-main-concepts/13-deployment.md
- packages/neo-one-website/tutorial/tutorial.md
- Adds documentation for new compiler transfers API to the website docs
- Adds the API to the ICO mixin and test coverage
- Removes `gasCost` from some tests (doesn't exist any more)
- Add notes to `compileContract.ts` for a potential new issue
- Fixes up debugger output for N3 compiler changes and changes to the debugger spec
- Fixes and cleans up the parsing of Actions produced by contract calls
- Cleans up `args.ts`
- Fixes notifications produced by our compiler by removing the redundant eventName item
- `TestICO.test.ts`
None.
- Transfers API documented
- Removes tons of bugs and cleans up the code
- Fixes notifications produced by compiler
Possibly introduced bugs made incorrect fixes.
#2410 
#2466 
#2475
> feat(compiler): add transfer api documentation and other fixes

- packages/neo-one-node-bin/src/cmd.ts
- packages/neo-one-node-offline/src/index.ts
- packages/neo-one-node/src/startFullNode.ts
- Updates chainfile sync and chainfile dump with "write start" and "read start". We now have the option to write/read the start block of the chainfile with the first four bytes. So it's possible that a chainfile has the start index instead of just the count first instead of the number of blocks. This allows for that now.
Tested manually. Works.
None.
Proper chainfile sync/dump in N3.
None.
#2410 
#2157
> feat(node): update node-offline chainfile sync for n3

- packages/neo-one-client-common/src/types.ts
- packages/neo-one-smart-contract-compiler/src/compile/compile.ts
- packages/neo-one-smart-contract-test/src/__data__/tokenUtils.ts
- Update invocation types considering @receive is currently not operational
- Update compiler version for RC3
None.
None.
Better UI.
None.
#2410
> fix(compiler): update compiler version for rc3

- packages/neo-one-website/blog/2021-07-02-neo-one-rc3-announcement.md
- Add blog post for RC3 release
https://n3.neo-one.io/blog/2021/03/18/neo-one-rc3-announcement
None.
Announcement.
None.
#2410
> feat(website): add rc3 blog post

- packages/neo-one-website/docs/0-installation/0-quick-start.md
- packages/neo-one-website/docs/0-installation/2-environment-setup.md
- packages/neo-one-website/docs/3-node/4-build-from-source.md
- packages/neo-one-website/tutorial/tutorial.md
- Fixes incorrect path for edge_app_root
None.
None.
Better UX.
None.
#2410
> fix(docs): fix edge_app_root documentation 2

- packages/neo-one-cli/src/deploy/runMigration.ts
- Fix deployment network fee to be no max.
None.
None.
Deploy works without network fee limit. So deploy works.
Deploy could burn a lot of GAS without user realizing it until it's too late.
#2410
> fix(deploy): fix deploy maxnetworkfee

- packages/neo-one-website/docs/0-installation/0-quick-start.md
- packages/neo-one-website/docs/0-installation/2-environment-setup.md
- packages/neo-one-website/docs/1-main-concepts/02-smart-contract-basics.md
- packages/neo-one-website/docs/3-node/4-build-from-source.md
- packages/neo-one-website/tutorial/tutorial.md
Windows users need to add environment variables. It is not clear that this step is mandatory (now it is). Also updated C# version to 3.1.404 and requested the user to verify the installed .NET version.
The node is now starting when we type `npx neo-one start network` on Windows.
> Documentation improvements.

- packages/neo-one-cli-common/src/deployContract.ts
- I mistakingly put the deployer's address as a parameter to any `build` command deployment. So anytime the `build` command is called it was passing in an argument to the deploy method even if it didn't accept one.
- But the problem is that if your contract does take in arguments for deploying then the user won't be able to during the `build` command. They will have to just set default arguments in the contract for testing. Or they will have to do the build command in separate steps.
Tested locally. This is how it was originally supposed to be anyway.
None.
Working build command.
See second bullet point above. But that was always the case anyway.
#2410 
#2491
> fix(deploy): fix build command

- packages/neo-one-smart-contract-compiler/src/compile/helper/arr/ArrRangeHelper.ts
- Remove `createMapIterator` from `ArrRangeHelper`
- `rush test -t packages/neo-one-smart-contract-compiler/src/__tests__/compile/builtins/object/keys.test.ts`
None.
Cheaper contracts/better compiler.
None.
#2448
> fix(compiler): remove createMapIterator from ArrRangeHelper

- packages/neo-one-node-blockchain/src/Blockchain.ts
- packages/neo-one-node-blockchain/src/__tests__/BlockchainE2E.test.ts
- packages/neo-one-node-protocol/src/Message.ts
- packages/neo-one-node-storage-levelup/src/__tests__/levelUpStorage.test.ts
- packages/neo-one-node-storage-levelup/src/__tests__/rocksDBStorage.test.ts
- packages/neo-one-node-storage-levelup/src/read.ts
- packages/neo-one-node-vm/lib/Storage/RocksDB/Snapshot.cs
- packages/neo-one-node-vm/lib/Storage/RocksDB/Store.cs
- Update logging for start of blockchain and for p2p message parsing errors
- Fix how P2P messages are parsed so that our stream waits for chunks accurately before trying to parse messages
- Fix the `Seek` method in Dispatcher so that the ApplicationEngine gets the correct byte array out of storage
Synced RC4 Node on staging
None.
Proper message parsing. Proper storage retrieval.
Possibly introduced unforeseen consequences by removing the byte array slicing in Snapshot.cs and Store.cs. Dan introduced these changes way back in Preview4 and I don't know why we would want to slice off the first byte of the keys from storage.
#2521
> fix(node): fix how p2p messages are parsed

- packages/neo-one-client-common/src/models/NefFileModel.ts
- packages/neo-one-node-protocol/src/Node.ts
- packages/neo-one-smart-contract-compiler/src/__tests__/compile/builtins/contract/linkedSmartContract/for.test.ts
- packages/neo-one-smart-contract-compiler/src/compile/builtins/contract/NativeContractCallValue.ts
- packages/neo-one-smart-contract-compiler/src/compile/builtins/contract/SmartContractForBase.ts
- packages/neo-one-smart-contract-compiler/src/compile/builtins/contract/block.ts
- packages/neo-one-smart-contract-compiler/src/compile/builtins/contract/blockchain.ts
- packages/neo-one-smart-contract-compiler/src/compile/builtins/contract/contract.ts
- packages/neo-one-smart-contract-compiler/src/compile/builtins/contract/linkedSmartContract/for.ts
- packages/neo-one-smart-contract-compiler/src/compile/builtins/contract/smartContract/destroy.ts
- packages/neo-one-smart-contract-compiler/src/compile/builtins/contract/smartContract/for.ts
- packages/neo-one-smart-contract-compiler/src/compile/builtins/contract/transaction.ts
- packages/neo-one-smart-contract-compiler/src/compile/compile.ts
- packages/neo-one-smart-contract-compiler/src/compile/helper/binary/BinaryDeserializeHelper.ts
- packages/neo-one-smart-contract-compiler/src/compile/helper/binary/BinarySerializeHelper.ts
- packages/neo-one-smart-contract-compiler/src/compile/helper/contract/IsCallerHelper.ts
- packages/neo-one-smart-contract-compiler/src/compile/helper/contract/UpgradeHelper.ts
- packages/neo-one-smart-contract-compiler/src/compile/helper/crypto/RIPEMD160Helper.ts
- packages/neo-one-smart-contract-compiler/src/compile/helper/crypto/SHA256Helper.ts
- packages/neo-one-smart-contract-compiler/src/compile/sb/BaseScriptBuilder.ts
- packages/neo-one-smart-contract-compiler/src/compile/sb/DiagnosticScriptBuilder.ts
- packages/neo-one-smart-contract-compiler/src/compile/sb/ScriptBuilder.ts
- packages/neo-one-smart-contract-compiler/src/compile/types.ts
- Add MethodTokens output to compiler
- Update Node's useragent and compiler's version number for MainNet
- Fix MethodToken serialize method
None.
None.
N3 MainNet
None.
#2449
> fix(compiler): add methodtokens to compiler, plus minor fixes

- packages/neo-one-smart-contract-compiler/src/__tests__/compile/builtins/contract/__snapshots__/blockchain.test.ts.snap
- packages/neo-one-smart-contract-compiler/src/__tests__/compile/builtins/contract/blockchain.test.ts
- packages/neo-one-smart-contract-compiler/src/compile/builtins/contract/BuiltinInstanceIndexValue.ts
- packages/neo-one-smart-contract-compiler/src/compile/builtins/contract/blockchain.ts
- packages/neo-one-smart-contract-compiler/src/compile/builtins/contract/transfer.ts
- packages/neo-one-smart-contract-test/src/__data__/contracts/TestICO.ts
- packages/neo-one-smart-contract-test/src/__tests__/TestICO.test.ts
- packages/neo-one-smart-contract-test/src/__tests__/__snapshots__/TestICO.test.ts.snap
- packages/neo-one-smart-contract/src/index.d.ts
- Fixes the `Transfer.amount` API in compiler to actually be a Fixed8 value
- Clarifies the `Blockchain.currentBlockTime` API to be in seconds instead of milliseconds
- Adds `Blockchain.currentBlockTimeMilliseconds` API to be block time in milliseconds.
- Adds tests and fixes tests for these changes.
Tests updated below.
None.
Better, clearer, cleaner APIs.
None.
None.
> fix(compiler): fixup transfer amount, current time apis

- packages/neo-one-client-common/src/models/types.ts
- packages/neo-one-client-core/src/Client.ts
- packages/neo-one-client-core/src/__tests__/nep17.test.ts
- packages/neo-one-client-core/src/nep17.ts
- packages/neo-one-client-core/src/provider/JSONRPCClient.ts
- packages/neo-one-client-core/src/sc/createSmartContract.ts
- packages/neo-one-node-rpc-handler/src/createHandler.ts
- Update `createSmartContract` and `Client` and `nep17` to allow users to call non-NEO•ONE contracts with these APIs. This is necessary because NEO•ONE contracts are currently called differently than other contracts. See #2476. This should be reversed when 2476 is fixed later.
- Add types to RPC handlers and fix return values for a few.
None.
More flexible client APIs
None.
#2476
> fix(client): allow nep17 and smart contract APIs for non-neo-one calls

- .github/workflows/website.yaml
- packages/neo-one-client-common/src/models/types.ts
- packages/neo-one-client-common/src/types.ts
- packages/neo-one-client-core/src/Client.ts
- packages/neo-one-client-core/src/__tests__/nep17.test.ts
- packages/neo-one-client-core/src/__tests__/sc/createSmartContract.test.ts
- packages/neo-one-client-core/src/nep17.ts
- packages/neo-one-client-core/src/provider/convert.ts
- packages/neo-one-client-core/src/sc/common.ts
- packages/neo-one-client-core/src/sc/createSmartContract.ts
- packages/neo-one-node-blockchain/src/Blockchain.ts
- packages/neo-one-node-blockchain/src/PersistingBlockchain.ts
- packages/neo-one-node-blockchain/src/errors.ts
- packages/neo-one-node-blockchain/src/getExecutionResult.ts
- packages/neo-one-node-core/src/Block.ts
- packages/neo-one-node-core/src/BlockData.ts
- packages/neo-one-node-core/src/Serializable.ts
- packages/neo-one-node-core/src/StackItems/InteropInterface.ts
- packages/neo-one-node-core/src/StackItems/StackItemBase.ts
- packages/neo-one-node-core/src/action/ActionBase.ts
- packages/neo-one-node-core/src/action/ActionType.ts
- packages/neo-one-node-core/src/action/LogAction.ts
- packages/neo-one-node-core/src/action/NotificationAction.ts
- packages/neo-one-node-storage-common/src/keys.ts
- Adds blockActions to blocks so that we can see what actions were produced by the postPersist and onPersist scripts run when persisting every block. This is primarily to get the burn and mint info from NEO and GAS native contracts.
- Adds apis to digest this information from the client.
- Updates NEP17 and client smart contract APIs to be more accurate and bug free.
- Updates node errors to be more descriptive.
- Updates Interop stack item to have toContractParameter method.
Use with NEO Tracker locally.
None.
Appropriate info produced and stored by node.
None.
None.
> feat(node): add block data for block action tracking

- packages/neo-one-client-common/src/models/nep17/Nep17TransferModel.ts
- packages/neo-one-client-common/src/models/types.ts
- packages/neo-one-client-common/src/types.ts
- packages/neo-one-client-core/src/provider/convert.ts
- packages/neo-one-client-full-common/src/models/manifest/ContractGroupModel.ts
- packages/neo-one-client-full/src/index.ts
- packages/neo-one-client/src/index.ts
- packages/neo-one-node-blockchain/src/Blockchain.ts
- packages/neo-one-node-blockchain/src/PersistingBlockchain.ts
- packages/neo-one-node-blockchain/src/getNep17UpdateOptions.ts
- packages/neo-one-node-core/src/Nep17Balance.ts
- packages/neo-one-node-core/src/Nep17BalanceKey.ts
- packages/neo-one-node-core/src/Nep17Transfer.ts
- packages/neo-one-node-core/src/Nep17TransferKey.ts
- packages/neo-one-node-core/src/StorageItem.ts
- packages/neo-one-node-core/src/contractParameter/ByteArrayContractParameter.ts
- packages/neo-one-node-core/src/contractParameter/ContractParameter.ts
- packages/neo-one-node-rpc-handler/src/createHandler.ts
- packages/neo-one-node-storage-common/src/keys.ts
- packages/neo-one-node-vm/lib/Dispatcher.Engine.cs
- Adds information to Nep17Transfer object so that it's easier to debug when transfers go wrong in our node in the future.
- Fixes some client code/types.
- Fixes global action indexes.
- Converts all base64 buffer strings from node into hex buffer strings.
- Commits almost all storages changes all at once instead of separately.
- Gets only the Fault error message from the VM instead of the entire stack trace as well.
None. Tested locally and in production.
None.
More transfer information stored. Bug fixes. Better types. Cleaner code.
None.
None.
> fix(node): add more info to nep17transfers
